README.rst
netCDF4 moved from Google code to Github.  Update links to the Github site.
=> Update link to netCDF4

pyart/graph/cm.py
The colormaps in pyart.graph.cm can now be used in matplotlib
by referencing them by a string of the form "pyart_COLORMAP" for example
"pyart_NWSRef".
Closes #198
=> ENH: colormaps registered for use by get_cmap()

pyart/correct/dealias.py, pyart/correct/tests/test_phase_proc.py, pyart/graph/plot_mdv.py, pyart/graph/radardisplay.py
No output is emitted from Py-ART when running unit tests using standard settings.
=> TST: Removed warnings and unnecessary screen output from tests

pyart/correct/unwrap_2d_ljmu.c, pyart/correct/unwrap_3d_ljmu.c
The dealias_unwrap_phase function no longer Segmentation faults when
a sweep in the passed radar object is fully masked or all the gates
are filtered.
Closes #230
=> BUG: No SegFault when dealiasing sweeps with all gates filtered

doc/source/dev_reference/correct.rst, pyart/correct/__init__.py, pyart/correct/_common_dealias.py, pyart/correct/region_dealias.py, pyart/correct/tests/test_region_dealias.py, pyart/correct/unwrap.py
Add the **dealias_region_based** function to the pyart.correct namespace which performs Doppler velocity dealiasing by finding regions of similar velocities and unfolding and merging pairs of regions until all regions are unfolded.  Unfolding and merging regions is accomplished by modeling the problem as a dynamic network reduction.
=> ENH: Region based Doppler velocity dealiasing

pyart/io/cfradial.py
Opening the same NetCDF files without closing the Dataset object
causes a segmentation fault on some systems.  This explicitly closes the netCDF4
Dataset object when the read_cfradial function is done extracting data from the
object.
=> BUG: NetCDF files close to prevent SegFault

pyart/io/rsl.py
While attempting to read in [NPOL DATA](ftp://gpm.nsstc.nasa.gov/gpm_validation/ifloods/NPOL/data) I encountered a bug in which reading the UF file failed because a volume number was not recognized.
```
File "pyart/pyart/io/rsl.py", line 122, in read_rsl
rsl_field_name = VOLUMENUM2RSLNAME[volume_num]
KeyError: 46
```
This hints that the VOLUMENUM2RSLNAME dict is out of date.  This change doesn't update the dict, but instead lets reading continue after logging a warning:
```
2015-01-22 10:54:04,253 WARNING root: Unknown Volume Number 46
2015-01-22 10:54:04,253 WARNING root: Unknown Volume Number 46
```
=> Fail softly when volume number is unknown

pyart/io/cfradial.py
The scan_type of a radar will be set to ppi if the string 'ppi' appears in
the first sweep_mode string when reading CfRadial files.
=> MAINT: Added fallback ppi scan type for CfRadial files

pyart/core/tests/test_grid.py, pyart/map/tests/test_map.py, pyart/testing/sample_objects.py
All grid related functions and class should use a z, y, x ordering
for shape and size.  Radar related functions may still use x, y, z.
=> MAINT: Fixed inconsistency in grid shape ordering

pyart/correct/unwrap.py
Specifying the unwrap_unit as 'sweep' or 'volume' supported when
unfolding VPT scans with the dealias_unwrap_phase provided the data
is stored as a single sweep.
=> BUG: Support for dealiasing vpt scans with dealias_unwrap_phase.

pyart/correct/filters.py
Adding an `inclusive` keyword to the relevant filter methods (e.g., exclude_below). This gives the user more control over the specifics and reduces ambiguity, for example, it's ambiguous as to whether the actual minimum and maximum values specified in exclude_inside (include_inside) will be excluded (included) or not unless the user dives into the actual code. One final point is that the default setting of the inclusive kwarg is consistent with what @jjhelmus originally intended with the filter methods.
=> ENH: inclusive kwarg to filters

pyart/io/__init__.py, pyart/io/common.py
add a function to create in grid object from the axes x_disp,y_disp,lat and lon, 2-d axes for the latitude or longitude of every point the the xy plane. The math is "simple" azimuthal equidistant projetion to latlon. I map it into pyart so I can call as a user, but one should decide how to implement, if as method in grid or something else
=> Latlon for points in grid

continuous_integration/build_docs.sh
* Fixes the failing build of the documentation on Travis CI.
* In the future when the documentation fails to build the CI build will fail.
=> TST: Fix failing documentation build on Travis CI

doc/source/dev_reference/index.rst, doc/source/dev_reference/util.rst, doc/source/user_reference/index.rst, doc/source/user_reference/util.rst, pyart/__init__.py, pyart/util/__init__.py, pyart/util/circular_stats.py, pyart/util/setup.py, pyart/util/tests/test_circular_stats.py
Add functions to calculate the mean and standard deviation for distribution of angles (in both radians and degrees) as well as distribution of samples taken over a circular interval.
These functions are useful when working with circular radar moments whose values are derived from phase based measurements, for example Doppler velocities, where conventional linear statistics are not appropriate.
=> ENH: Statistics on circular distributions

pyart/map/gates_to_grid.py, pyart/map/grid_mapper.py, pyart/map/tests/test_gates_to_grid.py, pyart/map/tests/test_grid_mapper.py
A common issue for users is forgetting that the grid_from_radars and underlying
function require a sequence as the first object and not a Radar object.
A one tuple is created when a single radar object is passed to these functions.
=> ENH: grid creation function accept a single Radar object.

pyart/graph/gridmapdisplay.py
Simple fix to change a confusing doc string.. This one has been bugging me for a while.
=> DOC: Fix docstring to remove confusion in gridmapdisplay.py

pyart/map/_gate_to_grid_map.pyx
Just a small bug. Please rebuild cython, I have problems doing in my computer because of isfinite
=> BUG: refl_filter_flag=False not working in map_gate_to_grid

pyart/correct/dealias.py
Adding the ability to input a radar `GateFilter` when dealiasing Doppler velocities with the James et al. (2001) 4-D algorithm. Note that certain kwargs are now deprecated (e.g., extra_prep) but I'll let @jjhelmus decide if these kwargs should be permanently removed or kept for backwards compatibility.
=> ENH: GateFilter available for 4DD

pyart/graph/radardisplay.py, pyart/graph/radardisplay_airborne.py, pyart/graph/radarmapdisplay.py
Add GateFilter instance (pyart.correct.GateFilter) as a keyword input to ```plot_ppi``` and ```plot_rhi``` in  ```radardisplay.py```.
If acceptable, it could be extended to the other display code. It's a relatively simple change. It will make building the ARTView masking procedure much easier and allow users to see changes of applying a masking filter to data.
=> Add GateFilter to RadarDisplay

pyart/aux_io/radx.py
Raise a IOError with a helpful message suggesting an upgrade to RadX when
the specified file is not created.
=> MAINT: Raise exception when RadxCovert does not create a file

pyart/io/mdv_grid.py
As this function is founding increasing use, I thought `mdv_field_names` and `field_write_order`  would be an important addition. Since I'm already here, is there something else that could be done?
=> add mdv_field_names to write_mdv_grid

pyart/io/cfradial.py
Added an error recovery measure for missing sweep_number parameters. I believe the parameter is fully redundant as long as fixed angles or sweep_start_ray_index exists. Also fixed a minor spelling error.
=> Made reader more resillient to missing sweep_number parameter

doc/source/dev_reference/util.rst, pyart/util/__init__.py, pyart/util/hildebrand_sekhon.py, pyart/util/tests/test_hildebrand_sekhon.py
Add the pyart.util.estimate_noise_hs74 which estimates the noise parameter of a
Doppler spectrum using the Hildebrand and Sekhon method
=> ENH: Hildebrand-Sekhon estimation of noise levels

pyart/graph/common.py, pyart/graph/radardisplay.py, pyart/graph/tests/test_radar_display.py, pyart/util/xsect.py
This PR is in response to Issue #398
=> Add plot azimuthal cross-section to radardisplay class.

pyart/core/grid.py
Adding the `replace_existing` kwarg to the `add_field` method of Grid. This is to be consistent with the Radar class and its add_field method. I know we plan on overhauling the Grid class but this method should be portable regardless of the changes to Grid in the future.
=> ENH: replace_existing in Grid

.gitignore, examples/plotting/plot_grid_three_panel.py, pyart/core/grid.py, pyart/core/tests/test_grid.py, pyart/core/transforms.py, pyart/default_config.py, pyart/graph/common.py, pyart/graph/gridmapdisplay.py, pyart/io/__init__.py, pyart/io/grid_io.py, pyart/io/mdv_grid.py, pyart/io/tests/test_grid_io.py, pyart/io/tests/test_mdv_grid.py, pyart/map/grid_mapper.py, pyart/map/tests/test_gates_to_grid.py, pyart/map/tests/test_grid_mapper.py, pyart/retrieve/echo_class.py, pyart/testing/sample_objects.py, pyart/util/datetime_utils.py, scripts/convert_legacy_grid
Introduce a new improved layout for the **Grid** class.  The new class has the following attributes:
* fields
* metadata
* time
* origin_latitude, origin_longitude, origin_altitude : specifying the geographic location of the grid origin
* x, y, z : specifying the regular Cartesian/cartographic distances from the grid origin.
* nx, ny, nz : the sizes of the three above dimensions.
* projection : specified the map projection used to transform between Cartesian and geographic coordinates.
* radar_latitude, radar_longitude, radar_altitude : Geographic location of the radar which were used to create the grid.
* radar_name, radar_time : Additional information about the radars which were used to create the grid.
* nradar : number of radar used to create the grid.
Additional the following …
=> ENH: New Layout from Grid

pyart/graph/radarmapdisplay.py
Sometimes you create a Basemap elsewhere and want to use it to plot radar data on. This enhancement allows you to plot a ppi on top of a separate Basemap, without creating a new Basemap every time you use plot_ppi_map. The example below leverages this new feature to simplify plotting a DEM, NPOL, and AMPR data all on the same Basemap instance, which is used in each of the 4 panels.
=> Added basemap keyword to RadarMapDisplay.plot_ppi_map

.travis.yml, continuous_integration/install.sh
All unit tests which depended on basemap or pyproj were being skipped on the Python 2.7 run on Travis CI due to a conda install issue with gdal and basemap.  Now these tests are run as intended.
=> TST: Fix skipped basemap tests on Travis CI

pyart/map/grid_mapper.py, pyart/map/tests/test_grid_mapper.py
When using the 'Barnes' weighting_function with map_to_grid, masked values in
the radar gates within the radius of influence are not included in the
interpolation of the grid point. Previously these values may have been
included in the interpolated grid point due to a bug in numpy.ma.dot
closes #443
=> BUG: Masked values not included in Barnes weights

pyart/config.py
correct the bug where `get_field_colormap` returned a colormap instance.This caused ARTView issue [#109](https://github.com/nguy/artview/issues/109)
=> BUG: get_field_colormap return string.

pyart/graph/__init__.py, pyart/graph/radardisplay_airborne.py
Changed name from RadarDisplay_Airborne to AirborneRadarDisplay.
Added an alias in pyart.graph.__init__.py
As discussed in Issue #364 to change name, very minor and easy fix. There is further discussion in there regarding time series, but I think that maybe a separate issue should be opened on how to handle that.
=> Airborne Display class name change

pyart/core/radar.py, pyart/graph/radardisplay.py, pyart/graph/tests/test_radar_display.py, pyart/util/datetime_utils.py
Updated datetime_utils to convert to Epoch time if desired.
Updated RadarDisplay.plot_vpt to accept a flag to use time along x-axis.
Added time formatting for x-axis for time-height plots.
This is a suggestion at implementing the time-height plots discussed in Issue #451 and also allows to conversion of Epoch time for future development (perhaps Issue #435 ?).
=> Time-height displays.

examples/plotting/plot_rhi_cfradial.py, examples/plotting/plot_rhi_sigmet.py, examples/plotting/plot_rhi_two_panel.py, pyart/core/grid.py, pyart/core/radar.py, pyart/core/tests/test_grid.py, pyart/core/tests/test_radar.py, pyart/core/tests/test_transforms.py, pyart/core/transforms.py, pyart/exceptions.py, pyart/graph/__init__.py, pyart/graph/_cm.py, pyart/graph/cm.py, pyart/graph/gridmapdisplay.py, pyart/graph/radardisplay.py, pyart/graph/radardisplay_airborne.py, pyart/graph/radarmapdisplay.py, pyart/graph/tests/test_cm.py, pyart/graph/tests/test_common.py, pyart/graph/tests/test_gridmapdisplay.py, pyart/graph/tests/test_radardisplay.py, pyart/graph/tests/test_radarmapdisplay.py
Refactor of **RadarDisplay**, **RadarMapDisplay**, **GridMapDisplay** and **AirborneRadarDisplay** to take into account the new layout and attribute of the **Grid** and **Radar** classes.  
Depreciate multiple unnecessary attributes of the **RadarDisplay** class:
* x, y, z
* starts, ends
* time_begin
* radar_name
Modification and additional unit tests for better coverage of the modules in the graph sub-package.
=> MAINT: Refactor of Display classes

pyart/core/__init__.py, pyart/core/transforms.py, pyart/io/__init__.py
Add functions from the transforms module to the `pyart.core` namespace so that they are in the public API.  Remove the deprecated `add_2d_latlon_axis` function from the User Reference Guide.
=> API: Add transform function to pyart.core

pyart/graph/common.py, pyart/graph/gridmapdisplay.py, pyart/graph/radardisplay.py, pyart/graph/radardisplay_airborne.py, pyart/graph/radarmapdisplay.py, pyart/graph/tests/test_common.py
The plotting method of the RadarDisplay, RadarMapDisplay, GridMapDisplay and
RadarDisplay_Airborne classes now accept a norm parameter which is passed to
the Matplotlib pcolormesh function as the norm parameter allowing for
customized scaling of the luminance data.
=> ENH: Add norm parameter to plotting methods

pyart/graph/radarmapdisplay.py, pyart/graph/tests/test_radarmapdisplay.py
Fix bug causing RadarMapDisplay.plot_range_rings to error due to an undefined
col parameter being passed to basemap.plot method.
=> BUG: RadarMapDisplay.plot_range_rings

pyart/correct/_common_dealias.py, pyart/correct/tests/test_region_dealias.py
Do not set the valid_min and valid_max entries in the dealiasing velocities
dictionary when all the velocities are masked.
=> BUG: Do not set valid_min/max if all data masked

pyart/io/cfradial.py, pyart/io/tests/test_cfradial.py
Elements of the instrument_parameter dictionary whose dimensions are not know
are skipped when writing Cf/Radial files using the write_cfradial function.
=> BUG: instrument parameter skipped if dim not known

pyart/default_config.py, pyart/graph/common.py, pyart/graph/gridmapdisplay.py, pyart/graph/radardisplay.py, pyart/graph/radardisplay_airborne.py, pyart/graph/radarmapdisplay.py, pyart/graph/tests/test_common.py
When plotting radar fields using the various **Display** classes if the colormap (cmap) and luminosity limits (vmin, vmax) are not specified then the defaults for these parameters will be determined by locating the field being plotted in a list of default colormaps and luminosity limits in the Py-ART configuration file.  
These parameters can still be explicitly specified.
=> ENH: Default field specific colormaps and luminosity when plotting

pyart/io/mdv_common.py, pyart/io/tests/test_mdv_common.py
A more informative error message is raised when trying to determine the
azimuth, elevation and range values for a MDV file in a projection type not
supported by Py-ART.
=> BUG: Better error message of unsupported MDV proj

continuous_integration/build_docs.sh, doc/source/_static/scipy.css, doc/source/conf.py
Documentation can be build using Sphinx 1.3.x, tested with 1.3.5
closes #375
=> BUG: Docs can be build in Sphinx 1.3

doc/rebuild_docs.sh, doc/rebuild_examples.sh, doc/rebuild_full_docs.sh, doc/rebuild_guides.sh, doc/source/conf.py
The default behavior when build the Py-ART documentation is to not build the
documentation for the examples. This can be changed by setting a
BUILD_PYART_EXAMPLES environment variables.  Alternatively one of the three
rebuild_ scripts in the docs folder can be used:
* rebuild_docs.sh : Rebuild standard docs, examples built only if variable set.
* rebuild_example.sh : Rebuild the example (and the other docs).
* rebuild_full_docs.sh : Rebuild the full docs including the examples.
If the examples have never been built a single warning will be raised about the
lack of examples.  This can be ignored.
=> DOC: Building of examples opt-in

.gitignore, examples/plotting/plot_rhi_contours_differential_reflectivity.py
This is the differential reflectivity example that Scott had discussed, I increased the opacity of reflectance map but not removed it because I wanted the example to cover how to add and adjust cmap alpha.
=> RHI contour example 2

pyart/graph/radardisplay.py, pyart/graph/radarmapdisplay.py
Added `ax` keyword to call to `plot_colorbar()` in `radarmapdisplay.py` to allow proper locations of colorbars in multi-panel plots.
After fix, colorbars are on the correct panels, not on the last panel plotted:
=> 	modified:   pyart/graph/radarmapdisplay.py

pyart/correct/phase_proc.py
Use Python 3 "true division" in the phase_proc module adding explicitly where
"floor division" (x // y) is needed.
=> BUG: Fix division in phase_proc module

doc/sphinxext/gen_rst.py, doc/sphinxext/numpydoc/comment_eater.py, doc/sphinxext/numpydoc/compiler_unparse.py, doc/sphinxext/numpydoc/docscrape.py, doc/sphinxext/numpydoc/docscrape_sphinx.py, doc/sphinxext/numpydoc/numpydoc.py, doc/sphinxext/numpydoc/tests/test_docscrape.py, doc/sphinxext/numpydoc/tests/test_phantom_import.py, doc/sphinxext/numpydoc/tests/test_plot_directive.py, doc/sphinxext/numpydoc/tests/test_traitsdoc.py, doc/sphinxext/numpydoc/traitsdoc.py, examples/correct/plot_attenuation.py, examples/correct/plot_dealias.py, examples/correct/plot_lp_phase_proc.py, examples/mapping/plot_map_one_radar_to_grid.py, examples/mapping/plot_map_two_radars_to_grid.py, examples/plotting/plot_grid_three_panel.py, examples/plotting/plot_nexrad_reflectivity.py, examples/plotting/plot_ppi_basemap_with_rings.py, examples/plotting/plot_ppi_sigmet.py, examples/plotting/plot_rhi_cfradial.py, examples/plotting/plot_rhi_contours_differential_reflectivity.py, examples/plotting/plot_rhi_data_overlay.py, examples/plotting/plot_rhi_mdv.py, examples/plotting/plot_rhi_sigmet.py, examples/plotting/plot_rhi_two_panel.py, pyart/core/transforms.py
The Py-ART documentation including the examples can now be build on Python 2 or Python 3.
closes #503
=> Python 3 support for building the documentation

pyart/correct/region_dealias.py, pyart/correct/tests/test_region_dealias.py, pyart/correct/tests/test_unwrap.py, pyart/correct/unwrap.py
Correctly set the field dictionary _FillValue entry and the MaskedArray fill_value attribute from the input velocity field in the dealiasing routines.
=> BUG: Set _FillValue in dealias routines

pyart/map/_gate_to_grid_map.c, pyart/map/_gate_to_grid_map.pyx, pyart/map/grid_mapper.py
The min_radius parameter in the ROI calculate is the minimum radius of
influence not an additional radius added to any additional radius calculated.
closes #516
=> BUG: Correct use of min_radius in ROI calculation

pyart/io/grid_io.py
Simple ImportError where `warn` was used instead of `warnings.warn`. Since this is found in `read_legacy_grid` and this will be deprecated in future Py-ART releases it's not a huge deal but a bug nonetheless.
=> BUG: ImportError on warn --> warnings.warn

pyart/aux_io/odim_h5.py
* Better Python 3 support for reading strings from ODIM H5 files.
* Bug fix effecting the azimuth angles reported for ODIM H5 files.
* Fallback for range determination in ODIM H5 files.
* ODIM H5 RHI files correctly report the azimuth angles and scan_type.
closes #530
=> Various fixed for read ODIM H5 files

pyart/io/auto_read.py, pyart/io/nexrad_level3.py
Add the ability to read the NEXRAD Level 3 files which contain a NOAAPORT
record seperator.
=> ENH: Read NEXRAD Level 3 with NOAAPORT seperator

pyart/io/nexrad_archive.py, pyart/io/nexrad_level2.py, pyart/io/tests/test_nexrad_archive_msg1.py, pyart/io/tests/test_nexrad_archive_msg31.py
The NEXRAD volume coverage pattern (VCP) is included in the radar.metadata
dictionary when NEXRAD Level 2 files which contain this information are read.
=> ENH: NEXRAD VCP included in radar metadata

pyart/io/grid_io.py, pyart/io/tests/test_grid_io.py
Allow writing of Py-ART Grid objects using write_grid where the radar_name
attribute of the grid contains empty strings.
closes #537
=> BUG: Writing grids with empty radar names

pyart/core/grid.py, pyart/core/radar.py, pyart/core/tests/test_grid.py, pyart/core/tests/test_radar.py
Enhancements to the Radar and Grid classes made in version 1.6.0 causes these classes to become non-picklable.  Being able to pickled these objects is a requirement for their use in multiprocessing.  These changes allows these objects to once again be pickled and adds unit tests to verify this characteristic.
=> ENH: Radar and Grid classes can be pickled and unpickled

README.rst, doc/source/dev_reference/correct.rst, pyart/correct/__init__.py, pyart/correct/despeckle.py
This PR brings despeckling functionality to the `pyart.correct` module, via two functions - `find_objects` and `despeckle_field`. The latter leverages the former to identify small regions of contiguous pixels in any and every sweep in a `Radar` object. User can specify field thresholds, size of speckles, provide an initial `GateFilter`, etc. Then, an updated `GateFilter` is returned to help mask out the speckles. For volumes with 360-deg PPIs, the sweep edges are checked and objects are relabeled if they match, accounting for the periodic boundary.
Here is an example of the application of `pyart.correct.despeckle_field` to a NEXRAD sweep. In (a) no filter has been applied. I've already calculated standard deviation of differential phase (SD_PHIDP), so in (b) we apply a `GateFilter` that …
=> Finding objects in scans and despeckling

pyart/core/transforms.py
The geographic_to_cartesian_aeqd function in the transforms module would return
arrays contains nan when numerical imprecision caused the argument of the
arccos function to be out of the valid domain [-1, 1]. Add logic to catch and
correct these cases.
=> BUG: Prevent nan being returned from transform

pyart/graph/radarmapdisplay.py, pyart/graph/tests/test_radarmapdisplay.py
Raise a ValueError when a cylindrical equidistant projection is used when
plotting data using the RadarMapDisplay class.  This projection does not
support coordinate transformations.
closes #556
=> MAINT: Raise error when cyl projections used

pyart/map/grid_mapper.py, pyart/map/tests/test_grid_mapper.py
Use the faster 'map_gates_to_grid' algorithm as the default gridding algorithm
when using the grid_from_radars function.
=> MAINT: Change default gridding algorithm

pyart/core/transforms.py
Prefer importing pyproj directly over the version of the library included with
basemap. The fallback is still to use the version included with basemap.
=> MAINT: Prefer importing pyproj over basemap

pyart/retrieve/__init__.py, pyart/retrieve/advection.py, pyart/retrieve/tests/test_advection.py, pyart/testing/__init__.py, pyart/testing/sample_objects.py
This pull request covers the calculation of the displacement between two grids using phase correlation and treating the grid as an image. The user must pick the field and the level. The code can return a number of pixels (tuple) or, using the time difference, a velocity. 
It also contains code to shift, using ndimage, a grid by a certain number of pixels and trim the edges. 
This is the first of two pull requests aimed at implementing advection correction into Py-ART. The next pull request will enable the addition of two grids by advecting them to a common time step. 
More detailed examples and cookbook recipes will also follow
=> Advection calculation and shifting of grids

pyart/io/cfradial.py
Some combinations of netCDF4 and numpy fail to read NetCDF files with a single
masked value.
=> BUG: Reading NetCDF files with masked data

pyart/correct/dealias.py, pyart/correct/tests/test_dealias.py
Raise a ValueError when more than 999 sounding heights are provided to the
dealias_fourdd function.  This prevents a segmentation fault from occuring in
the C code of the FourDD algorithm.
Modifying the C routine where this limit is imposed to something larged (~5000)
would be reasonable but this change should wait until after the next release
in order for this error to be caught.
closes #571
=> BUG: Raise an error for too much sounding data

pyart/filters/__init__.py, pyart/filters/gatefilter.py, pyart/util/__init__.py, pyart/util/sigmath.py
Dear Py-ART users,
I have added the following functions:
In filters/gatefilter.py:  moment_based_gate_filter2 filters out gates according to radial textures
In util/sigmath.py: texture_along_ray computes the texture along a a ray with a user defined length.
Please let me know if this is up to standard.
Jordi
=> New gate filter based on texture of polarimetric variables

pyart/io/nexrad_level3.py
Fixes a bug when reading NEXRAD Level 3 produce 135 (Enhanced Echo  Tops) files
which prevented the data from being properly read.
=> BUG: bugfix for reading NEXRAD L3 product 135 (EET)

pyart/io/auto_read.py
Files which are only support by RSL can be read with pyart.io.read.  Previously
attempting to read these files with pyart.io.read would result in a NameError
as the _RSL_AVAILABLE variable was not imported into the auto_read.py module.
closes #589
=> BUG: pyart.io.read can read RSL only files

pyart/aux_io/rainbow_wrl.py, pyart/correct/__init__.py, pyart/correct/bias_and_noise.py, pyart/correct/noise.py, pyart/retrieve/__init__.py, pyart/retrieve/simple_moment_calculations.py, pyart/util/__init__.py, pyart/util/radar_utils.py, pyart/util/xsect.py
Dear Py-ART users,
I have added the following functionalities to Py-ART:
- A correction of RhoHV for noise in correct/noise.py
- The computation of the new fields: noise in dBZ, signal to noise ratio, logarithmic RhoHv (L parameter), and circular depolarization ratio in retrieve/simple_moment_calculations.
- A cross-section of a volume of RHIs along particular azimuths (pseudo-PPI) in util/xsect.py
@jjhelmus, I think we should set standard names for the new fields.
Let me know if you think these new functionalities can be implemented in Py-ART and are up to standard.
Jordi
=> Computation of secondary moments, noise correction of RhoHV and pseudo-PPI from RHI volume

pyart/aux_io/odim_h5.py, pyart/aux_io/rainbow_wrl.py
The dtype parameter was not added to NumPy's linspace function until version
1.9.0.  To support older versions of NumPy use the astype method instead.
closes #601
=> BUG: Change use of dtype in linspace function

setup.py
NumPy 1.11.2 contains a bug which prevents submodules from being built
correctly on Python 3.4 unless importlib.machinery has been imported at some
time.
=> BLD: Add kludge to setup.py script for Python 3.4

pyart/io/arm_sonde.py, pyart/io/tests/test_arm_sonde.py
Read in the altitude directly from ARM sonde files from the alt variable.
Previously the altitude/height was calculated from the pressure which would
give slightly incorrect values.
closes #606
=> BUG: Read in altitude form ARM sonde files

pyart/aux_io/rainbow_wrl.py
to read single `startangle` and dual `startangle` and `stopangle`  in multi-element ray_info
Following the discussion in #610 this PR fixes the issue for now.
fixes #609 
supersedes #610
=> FIX: fix _get_angle-function

pyart/aux_io/radx.py
Added a keyword argument to pyart.aux_io.read_radx radx_dir which allows for the
user to define a local (non-root) install of RadX. This should be very handy for
users who just want to drop in the pre-compiled radx binaries. Tested on OSX
sierra with CPOL RAPIC files.
=> ENH: Added local install option for radx

.gitignore, pyart/core/tests/test_wind_profile.py, pyart/core/wind_profile.py, pyart/io/arm_sonde.py
Adding latitude and longitude parameters/attributes to `HorizontalWindProfile` class. This information is now parsed from ARM radiosonde datasets in `read_arm_sonde`. I also considered adding `sample_time` as an optional parameter/attribute to the class, e.g., 1D array of datetimes, but thought otherwise. Let me know if I should add this as well, seeing as this information is available from standard soundings.
=> ENH: location data available in HorizontalWindProfile class

pyart/io/nexrad_level2.py
Convert set literal to tuple.
Resolves: #621
=> Fix syntax error under python 2.6.x

.travis.yml, README.rst, continuous_integration/environment-3.6.yml
Add Python 3.6 to Travis CI test matrix.
Add Python 3.6 to tested version in README.rst file.
=> Add support for Python 3.6

pyart/correct/__init__.py, pyart/correct/dealias.py, pyart/correct/tests/test_dealias.py
* Remove the deprecated `find_time_in_intep_sonde` function from pyart.correct.  `pyart.io.read_sonde_vap` should be used in its place.
* Remove the deprecated `sounding_heights`, `sounding_wind_speeds`, `and sounding_wind_direction` parameters from the `pyart.correct.dealias_fourdd` function.  These parameters should be specified using the `sonde_profile` argument.
=> Deprecate dealias sonde function and parameters

continuous_integration/environment-2.7.yml, continuous_integration/environment-3.4.yml, continuous_integration/environment-3.5.yml, continuous_integration/environment-3.6.yml, continuous_integration/install.sh
All packages used for Travis CI test are loaded from conda-forge or the default conda channels.  
Install cvxopt into Python 2.7 channel from conda-forge.
=> TST: Do not use jjhelmus channel for Travis CI test environment

pyart/correct/phase_proc.py
There was no way to set the coef for relation between KDP and Z in the LP Phase
processing. It was hard set to C-Band. Some how we dropped this in a version.
=> FIX: Coef in B-Matrix

pyart/graph/radardisplay.py, pyart/graph/radardisplay_airborne.py, pyart/graph/radarmapdisplay.py, pyart/graph/radarmapdisplay_cartopy.py
This PR addresses the issue of large file size outputs in `plot_ppi*` displays when creating vector graphics for publications.  If saving to pdf, eps, or svg output, `pcolormesh` was rendering many polygons, and not clipping those polygons to the plot window, meaning that for high resolution data, the output file sizes were huge (sometimes exceeding 100 megabytes), and editing the resulting images in graphics software such as Illustrator was difficult.  Such large files are also a world of pain in the publication process.
The PR introduces the raster keyword, which, when set to True, will cause the artist (`pcolormesh`) to use `pm.set_rasterized(True)`.  Behavior is described here: [http://matplotlib.org/api/_as_gen/matplotlib.artist.Artist.set_rasterized.html](http://matplotlib.org/api/_a …
=> added Raster keyword for happier vector file output

pyart/io/cfradial.py
This is a fix for a problem I had after an update (netcdf4 1.2.8 np112py36_0).
`type(netCDF4.chartostring(sweep_mode['data'][0])[()])` is `numpy._str` and there is no `decode` attribute in numpy._str
Because all strings are already in unicode in python we can drop the `decode('utf-8')`.
=> AttributeError fix with python 3.6 in cfradial.py

pyart/io/tests/test_cfradial.py
Test now does assert for both versions of netCDF4 by testing for
['azimuth_surviellance'] and [b'azimuth_surviellance'] as netCDF4.chartostring
sets unicode.
@scollis, should be good now.
=> TST: Fix for the sweep_mode assert in cfradial test.

pyart/aux_io/odim_h5.py
I had a problem when I tried to open an ODIM HDF5 file. This bug comes from H5Py, not pyart. This error is explained here:
https://github.com/h5py/h5py/issues/218
I just made a little change in pyart.aux_io.odim_h5.py to fix this bug.
=> H5Py OSError: File close degree doesn't match fix

pyart/core/tests/test_radar.py
Tests involving gate_x_y_z were failing most likely due to numpy 1.13. The radar gate arrays are now float32 in the newer version of numpy. Older version, gate arrays are float64. Still working on why the arrays dtype changed.
The atol values for the numpy.testing.assert_allclose tests were
changed for lower precision to better reflect the dtype change. The
tests changes work for both the newer and older versions of numpy.
=> TST: Fix for numpy 1.13 update.

pyart/filters/__init__.py, pyart/filters/gatefilter.py, pyart/filters/tests/test_gatefilter.py, pyart/util/__init__.py, pyart/util/sigmath.py
I have added a much faster velocity texture calculation and placed it into a subroutine into pyart.filters that returns a velocity texture field dictionary.
=> ADD: Velocity texture calculation into pyart.filters

pyart/correct/despeckle.py
I had this error while using pyart.correct.despeckle:
File "pyart/correct/despeckle.py", line 144, in despeckle_field
gatefilter=gatefilter, delta=delta)
File "pyart/correct/despeckle.py", line 85, in find_objects
gatefilter=gatefilter)
File "pyart/correct/despeckle.py", line 412, in _get_data
data = data.filled(fill_value=BAD)
File "numpy/ma/core.py", line 3687, in filled
fill_value = _check_fill_value(fill_value, self.dtype)
File "numpy/ma/core.py", line 485, in _check_fill_value
raise TypeError(err_msg % (fill_value, ndtype))
TypeError: Fill value 1e+20 overflows dtype int16
I don't know why the dtype is int16 (I'm using numpy 1.12 and python 3.6) but that was fixed by changing the global constant BAD to 9999.
=> OverflowError: Python int too large to convert to C long in despeckle

index.html
Remove link to Jonathan Helmus' contact information and suggestions to contact
him directly from the Py-ART landing page.
=> Remove jhelmus contact info from landing page

pyart/retrieve/kdp_proc.py
Hi,
In my Kdp retrieving routines I have had some issues with using the standard Python function range. I have solved this by using numpy's arange instead. This is a very minor change.
Cheers,
Daniel
=> Fixed issue with range()

pyart/io/_sigmet_noaa_hh.py, pyart/io/_sigmetfile.pyx, pyart/io/chl.py, pyart/io/mdv_common.py, pyart/io/nexrad_level3.py, pyart/io/uffile.py, pyart/testing/data/dummify_nexrad_file.py
Changed all files, but nexrad2 (already addressed in #700) in pyart that needed np.fromstring changed to np.frombuffer. We'll see what the tests show. Should only show basemap and nexrad2 with warnings because basemap is a dependency and the nexrad2 pull request is pending. If anything looks off let me know.
=> DEP: Changed fromstring to frombuffer to removed depreciation.

continuous_integration/build_docs.sh
@scollis With some researching online it seems pillow is preferred now over pil, with installing pillow, you can still do an import PIL or from PIL import Image. pil isn't playing nicely with geotiff or poppler dependencies of the dependencies, which are downloaded from the .yml env during the 2.7 test. pillow however has no issue being conda installed with sphinx when that line of code was originally failing with pil.
https://support.enthought.com/hc/en-us/articles/207704216-Use-Pillow-instead-of-PIL-for-Python-Imaging
=> FIX: Should fix the CI fail for 2.7 doc build. Let us see if CI test for 2.7 passes.

README.rst
Link in README was outdated and the link has been updated to wradlib's docs latest page.
=> DOC: Noticed link to wradlib was to the old bit bucket page, no longer exists.

pyart/correct/src/dealias_fourdd.c
This PR is to address #690 (pinging @pjmarinescu ). I replaced the findRay function with a completely new and simplified function. I then check in the continuity_dealias function to make sure that the spacing is reasonable. This seems to fix the error, although I would definitely appreciate a second look. 
On our first look at the data, it looks like for the specific file that we're working with, it looks mostly okay, with some small oddities that could also be related to needing to QC the original data. 
As an aside, I don't think that my spacing variable makes a lot of sense- it's identical to the one in the original code, but the indices (0 and 50) seem arbitrary or specific to some radar. I'm not quite sure what that's doing, so I'm open to changes. For reference, the spacing is …
=> Fixing infinite loop in 4DD algorithm

doc/sphinxext/numpydoc/numpydoc.py
Removed deprecated import of sphinx.util.compat.
https://github.com/ribozz/sphinx-argparse/issues/65
=> FIX: Fixing docbuild failure in Travis.

pyart/map/grid_mapper.py
Addressing Issue #682, this code adds a `Nearest` keyword to `map_to_grid` to perform nearest neighbor gridding (useful for gridding polar hydrometeor classification data, etc.).
Note that this keyword option is not available in `map_gates_to_grid`, which is the application that has been optimized by @jjhelmus in C.
=> added 'Nearest' keyword to 'map_to_grid'

README.rst, pyart/aux_io/rainbow_wrl.py, pyart/bridge/wradlib_bridge.py
- closes #722 
- fixes links to wradlib
- fixes import of `read_rainbow`
=> Fix wradlib 

index.html
Removed broken link for ARM radar group. Added more optional dependencies links, wradlib and gdal. Added link to contributor's guide. Fixed some typos, and added link to Anaconda Cloud.
=> DOC: Added more links to optional dependencies, removed broken links.

pyart/io/tests/test_mdv_radar.py
This is mentioned in issue #703 .
=> FIX: def test_rhi_elevation was used twice, the other should be named after field data.

pyart/aux_io/odim_h5.py
This patch adds support for "VRADH" and "VRADV" quantities as specified in ODIM HDF5 version 2.2.
=> Add VRADH and VRADV quantities to ODIM HDF5 decoder

pyart/io/mdv_grid.py
While reading MDV warns for unknown 'vlevel_type', set units to 'unknown' and continue
=> allow reading from MDV with unknown vertical level

pyart/graph/radarmapdisplay_cartopy.py
This is in response to issue #743. A warning is now raised when a user doesn't define a projection when setting the axes when creating a map display. 
When an axes is set but no projection is defined, the program will override the defined axes and change it to the default along with a default projection. A user will now be warned when this happens.
=> FIX: Added a warning messsage when an axes is defined without a projection

pyart/graph/radarmapdisplay_cartopy.py
A temporary fix suggested by @dopplershift that sets the pcolormesh axes to matplotlib axis until geoaxes in cartopy is updated for matplotlib 3.0.0.
=> FIX: This is a temporary fix for Cartopy issue #1120.

pyart/retrieve/__init__.py, pyart/retrieve/qvp.py, pyart/retrieve/tests/test_qvp.py
Code is based on adapted code from Scott Collis using the method found in Ryzhkov et all (2013, 2014, 2015)
Function will create a QVP dictionary with fields from a radar object. Testing of the code was done using radar scans and creating a time series plot and well as testing it against the unit test. 
Attached are some example time series plots
=> ADD: added a function that will make a QVP object from a radar object 

pyart/_debug_info.py, pyart/core/grid.py, pyart/core/tests/test_grid.py, pyart/core/transforms.py, pyart/lazydict.py
I removed basemap from the core modules, which pyproj from basemap is being used in these modules. I set the code to just use proj from pyproj until I integrate cartopy projections into grid.py etc. Also fixed missing import in grid.py of an exception and added a temporary try statement to remove a deprecation warning in lazy_dict.py. The try statement will be removed once we remove python 2.7 support.
=> MAINT: Removal of basemap from core modules and some fixes.

continuous_integration/environment-2.7.yml
Our CI breaks for Python 2.7 at the geotiff creation. This seems due to a dependency and packaging issue with GDAL. Current env seems to pull GDAL from a Cartopy dep. Now we try specifically installing GDAL
=> FIX: CI fix. explicit add of GDAL for py2.7

pyart/aux_io/arm_vpt.py, pyart/aux_io/d3r_gcpex_nc.py, pyart/aux_io/gamic_hdf5.py, pyart/aux_io/noxp_iphex_nc.py, pyart/aux_io/odim_h5.py, pyart/aux_io/rainbow_wrl.py, pyart/aux_io/sinarame_h5.py, pyart/config.py, pyart/io/cfradial.py, pyart/io/chl.py, pyart/io/grid_io.py, pyart/io/mdv_radar.py, pyart/io/nexrad_archive.py, pyart/io/nexrad_cdm.py, pyart/io/nexradl3_read.py, pyart/io/rsl.py, pyart/io/sigmet.py, pyart/io/uf.py
In response to #780 raised by @vlouf I have added an include_fields parameter to pyart.io.read and pyart.aux_io.read functions. If it is set to None, all of the fields that are not in exclude_fields will be loaded. Otherwise, it will only load the fields that are in include_fields.
I have not tested it for any of the aux_io cases as we don't have unit tests set up for those, but it works for all of the example files in the Py-ART testing suite.
=> ADD: include_fields parameter

examples/plotting/plot_ppi_basemap_with_rings.py, examples/plotting/plot_ppi_cartopy_with_rings.py
Updated the plot_ppi_basemap_with_rings.py with the RadarMapDisplayBasemap function and added a new example called plot_ppi_cartopy_with_rings.py which uses the updated RadarMapDisplay function with cartopy. 
Example will not work until PR #791 is accepted
=> New and updated plot_ppi examples for basemap and cartopy

pyart/aux_io/sinarame_h5.py, pyart/retrieve/gate_id.py
Try and except import error is now used instead of system check as suggested by @jimgeorge
=> MAINT: Updated cftime import as suggested in issue #738

pyart/io/nexrad_archive.py
This is a wee fix to grab the icao name from the volume header that exists. I believe it should work for either python2 or 3.
Also, if I followed the keywords correctly, it doesn't appear that [volume_header](https://github.com/ARM-DOE/pyart/blob/master/pyart/io/nexrad_level2.py#L110) or vcp keywords in the `NEXRADLevel2File` object are used?
=> Attempt to grab icao from Nexrad header

pyart/correct/region_dealias.py
I have reimplemented the optimization loop in the region based dealiasing to be faster and to have an extra term that adds a cost for correcting a region too far from the one with the closest mean velocity (i.e. it keeps regions of similar velocity together to better handle cases that may deviate far from the sounding).
=> ENH: Faster optimization loop in region based dealiasing + extra continuity term

pyart/correct/attenuation.py, pyart/correct/phase_proc.py, pyart/correct/region_dealias.py
I have done the following changes to Py-ART that needed to be done in the course of running CMAC2.0 on the X-SAPR data:
* Reorgainzed documentation for the MeteoSwiss attenuation correction codes and added a gatefilter to each of them.
* There was an issue where the phase processing code would crash if the freezing level was below the radar. For the LP phase processing, when the freezing level is below the radar it will default the mask to the smallest possible window size that can be provided to the filter in the LP processing code (6th gate in the ray and closer).
=> Atteunation correction fixes

pyart/io/nexrad_archive.py
Temporary fix to issue #772. Before 360 would be added to any negative angle and would read funny, now if any angle is above 45 degrees 360 will be subtracted. For example a fixed angle of -0.2 use to be outputted as 359.2, now it will be output as -0.2. Will be testing to get a more permanent fix for a future PR.
=> FIX: added argument to deal with negative fixed_angles

continuous_integration/install.sh
pytest-cov needs to be lower then version 2.6 to work with pytest and python 3.4.
=> CI: Fix for Python 3.4 issue with pytest. 

pyart/map/_gate_to_grid_map.pyx, pyart/map/gates_to_grid.py, pyart/map/grid_mapper.py
After discusssion with @robwarrenwx and @joshua-wx, Barnes was off from Pauley and Wu 1990 recommendation. This adds the weight function that is consistent with Barnes and Pauley and Wu. Added warnings for regular Barnes weight function in Py-ART, added references and fixed some spacing in doc strings. Pauley and Wu ROI will be in a separate pull request. This is a trial and barnes 2 isn't default to not impact operational uses for groups.
=> ENH: Adding Barnes 2 weighting function.

pyart/core/radar.py
`radar.extract_sweeps` changes the `sweep_start_ray_index` and `sweep_end_ray_index` datatype from int32 to int64. To keep consistent with the rest of the PyART library, the array['data'] numpy arrays are typed to int32
=> Force typing to match sweep indices elsewhere.

pyart/io/nexrad_level2.py
This addresses #826 which was caused by incomplete message 5's and extra empty scans that were written in the file. Py-ART will now simply skip over both of these and throw a warning if there is an odd-sized MSG5.
=> FIX: Skip empty scans and incomplete MSG5's

examples/plotting/plot_grid_data_overlay.py, examples/plotting/plot_grid_three_panel.py, examples/plotting/plot_three_panel_gridmapdisplay.py, pyart/graph/tests/test_gridmapdisplay_basemap.py
Created a new example that using the updated GridMapDisplay Class that shows how to set up axes and projection since it uses cartopy instead of basemap. Updated old examples so they use GridMapDisplayBasemap. Updated the unittest for test_gridmapdisplay_basemap and added an _basemap to the functions that needed them so they wouldn't have the same names as those in test_gridmapdisplay.py
=> Created  new eaxmple

pyart/aux_io/odim_h5.py
Current ODIM reader assumes the number of bins between sweeps is constant, as long as range start and scale are constant between sweeps. This doesn't hold true for new data from ECCC S-Band radars, range can be variable between sweeps. Proposed fix checks all sweeps for the `nbins` attribute, and finds the max.  Axis 1 of the numpy array for field data `fdata` is set to `max_nbins` rather than just `nbins` read from the first sweep. If a sweep has less bins than the max, these are set to `NaN`s. File is attached for testing.
[2018050823_12_ODIMH5_PVOL6S_VOL_CASRA.h5.zip](https://github.com/ARM-DOE/pyart/files/3122169/2018050823_12_ODIMH5_PVOL6S_VOL_CASRA.h5.zip)
=> Fix for reading ECCC ODIM files

pyart/io/grid_io.py
In write point function, the z, y, x dimensions were flipped which was
different then the original data. NetCDF4 new broadcasted_shape function
caught this.
=> FIX: A fix for a bug in grid io which had dimensions out of order.

pyart/aux_io/d3r_gcpex_nc.py
read_d3r_gcpex_nc function will have a default value of 295.0 even though netCDF file provide the correct value of the altitude.
This fix will allow the users to specify if they want to read the altitude from the provided netCDF file or use the default one.
=> Allow read_d3r_gcpex_nc function to read the altitude variable from netCDF file

README.rst, guides/contributors_guide.rst
Some clarification in the docs on creating and using anaconda environments. Also removed mention of fortran compiler because it is no longer needed. Nose was still mentioned in contributor's guide so switched it to pytest.
=> DOC: Remove fortran bit and added info on conda environments. Removed nose from contr guide.

pyart/core/grid.py, pyart/io/grid_io.py
When creating a grid object and saving it, a user now has an option to add the ARM standard alt, lat, lon variables if they want them added. Works the same as adding the ARM standard time variables.
=> ENH: Added argument in io/grid_io.py and core/grid.py  

pyart/graph/gridmapdisplay.py
Rounding has been changed to decimal 2 instead of 0 and 1. added .1 in both directions also.
=> MNT: rounding is causing lat and lon lines with data outside plot.

pyart/graph/_cm_colorblind.py
Caused by difference of floats and integers subtraction between python versions.
=> FIX: Fixes colorbar issue for HomeyerRainbow colormap

pyart/aux_io/odim_h5.py
Some how reading South African ODIM files yields an array for max_nbins.. doing a check for that..
=> FIX: ODIM reader with nbins being an array

pyart/graph/cm.py, pyart/graph/cm_colorblind.py
From what I'm reading, there is some disagreement between numpy and python on comparisons. For now I added a ignore warning until I can find maybe a better solution.
=> MAINT: Temp fix for warnings in colormap modules.

pyart/io/cfradial.py
After discussion, assigning the fillvalue to be in a specific order is removed as not seeing it as needed. Should fix error with unit tests.
=> FIX: Fixes fill value issue with netCDF4.

continuous_integration/environment-2.7.yml, continuous_integration/environment-3.6.yml, continuous_integration/environment-3.7.yml
Basemap plotting code will still exist in pyart, but there will be no support for it.
=> CI: Removing basemap as dependency in unit tests, support ends soon 2020, fails CI with 2.7.

pyart/graph/radarmapdisplay.py
I honestly had an issue trying to pinpoint the origin of the issue, most like geos as shapely and cartopy have not had recent updates that relate. In a nutshell, from testing, it seems that geos class returned changed from GEOMETRYCOLLECTION to LINESTRING, and when empty, one has and one doesn't seem to have an xy attribute. Regardless the value return to is None, so
if an empty class appears, None is appended to the ticks list as originally intended in the old code.
=> FIX: Fixes possible geos update that broke point calculation for lambert ticks.

pyart/graph/radardisplay_airborne.py
Addresses #829 by adding an argument, `ignoreTilt`, to the `plot_sweep_grid` function within `RadarDisplayAirborne` which will plot relative to slant range. The default (original) behavior plots relative to the aircraft longitudinal axis. An example illustrating the difference between the two behaviors is provided below.
=> Added option to ignore tilt angle in `plot_sweep_grid`

pyart/map/gates_to_grid.py, pyart/map/grid_mapper.py
As suggested by @vlouf in #863 , roi_func uses constant if constant_roi is not None.
=> MNT: Suggested changes of automatically setting roi_func to constant if constant_roi is used.

pyart/aux_io/kazr_spectra.py, pyart/correct/phase_proc.py
The parameter nowrap wasn't being used correctly and in kazr spectra 'is not' should not have been used for checking a float.
=> MNT: New warnings on literals, and a fix for said warnings.

doc/source/notebooks/basic_ingest_using_test_radar_object.ipynb
A fix for #916 the nrays and ngates in make_empty_ppi_radar were reversed. I fixed the revered inputs, the rest of the notebook should be fine as when the data for range and azimuth are populated they overwrite the incorrect numbers, but this fixes the incorrect empty object.
=> FIX: A fix for reversed ngates and nrays.

pyart/default_config.py, pyart/io/nexrad_level3.py
While I was combing through the ICD I realized there's a version number for each product included in the product description block that should be a good way to check that the product hasn't changed to a new version that is not supported by Pyart. If it has it issues a warning which hopefully should cause someone to take a look at the most recent ICD and verify there are no major changes.
I used the product version numbers in the table on pages 3-35 and 3-36 of the ICD FOR THE RPG TO CLASS 1 USER - Build 18.0.
I did not add version checking for the metadata parts that come before each product's data. I think there's a potential for these to change from build to build in a way that could break something, but also a greater potential to result in annoying warnings for no reason.
The good …
=> ADD: Nexrad Level 3 Product Version Checking

.gitignore, pyart/io/nexrad_level3.py, pyart/io/nexradl3_read.py
Many Nexrad Level 3 files have elevation angle defined by Halfword 30 of the product description block, but not all. (Elevation angle is not relevant for all products.)
Added a list of products for which elevation angle is defined by Halfword 30 per Table V of the ICD. For products for which it is not defined added logic to return data as None.
=> FIX: Elevation Angle for some products

pyart/retrieve/kdp_proc.py
I noticed that when writing a netCDF using write_cfradial for example, in the case a pyart field has a mask with all False (i.e. no masked values), it gets "compressed" to a single scalar boolean False. Parts of the Kdp processing codes couldn't handle that properly and assumed the mask to always be 2D. This fixes this particular case.
=> Fix in filter_psidp in case of scalar mask

pyart/io/output_to_geotiff.py, pyart/io/tests/test_output_to_geotiff.py
Since we are just renaming, using os, shutil behavior may have changed.
=> MNT: Attempt to fix appveyor path issue.

pyart/map/grid_mapper.py
When looking into the gatefilters issue #940, I noticed gatefilter in map_to_grid was broken due to the masked iterator behavior. Found a fix by flatten() the arrays to avoid the sequence error.
=> FIX: Fix for missing gatefilter in map_to_grid.

pyart/core/radar.py
Take absolute value of gate area to avoid returning negative areas. This covers cases where azimuth is decreasing instead of increasing. Thanks to John Krause for the suggestion.
=> FIX: add_gate_area now returns only positive values

pyart/map/grid_mapper.py
New parameter copys original radar fields dtype over to the grid.
@scollis @vlouf This should do what is requested in #955 . I added it as a parameter though to grid_from_radars.
=> ENH: Adding copy_field_dtype to grid mapper.

pyart/map/gates_to_grid.py, pyart/map/grid_mapper.py
This is the same PR as [#990](https://github.com/ARM-DOE/pyart/pull/990) (reopened as I have forgotten to add the check to the `map_to_grid` function).
In some edge cases (in my case when radars tuple is created in a loop) the empty tuple can be passed to the `gates_to _grid` or `map_to_grid` functions. In that case`tuple index out of range` error occures when `radars[0].altitude['data']` is acessed, and it is not always obvious what is the cause of that error.
I propose to add a simple check if `radars` tuple length is equal to 0. If yes then ValueError exception is raised with a more meaningful error message indicating what the issue is.
The placement of that `if` statement is just after conversion of single `Radar` object into `radars` tuple, so that tuple length can be checked without …
=> Add check if radars tuple is not empty

pyart/aux_io/gamicfile.py
When running in python 3, the format was kept as bytes and it would fail to load the data.
=> FIX: Correctly decode format from bytes to str

pyart/aux_io/gamicfile.py
GAMIC volumes support data in float32 format. The data contains the moment value directly, without need for conversion. The special value "NAN" is used to denote masked data.
=> ENH: Enable support for float32 data in GAMIC volume format

pyart/aux_io/gamic_hdf5.py
GAMIC's volume doesn't mandate the real scan_rate to be stored,
so we initialize scan_rate to the same value as the target_scan_rate.
=> ENH: Default scan_rate to target_scan_rate

examples/mapping/plot_map_one_radar_to_grid.py, pyart/io/cfradial.py, pyart/map/gates_to_grid.py, pyart/map/grid_mapper.py
`pyart.map.map_gates_to_grid` and `pyart.map.map_to_grid` emit deprecation warning that Barnes weighting function is deprecated, and suggest using Barnes 2. 
I propose changing the default weighting function to Barnes 2 in those two functions. Therefore less experienced PyART users will not be confused which function they should use. Advanced users still can change the function manually by kwargs. 
This PR also includes a few typo corrections in the documentation.
=> Change default weighting function to Barnes2 

pyart/default_config.py, pyart/io/_sigmetfile.pyx
Hi! I added support for reading PMI, LOG and CSP data types from Sigmet files for personal use and thought that they might useful for others as well, so here's a pull request! 
I did not add the `_sigmetfile.c` changes here, since running cython seemed to add some numpy version changes or something, and I was not sure which changes were actually related to this pull request. But if I should also add that file, I'll be happy to do so!
These data types are listed in the 2021 version of the IRIS Programming guide, so the section numbers in the comments refer to that.
=> ENH: Support for Sigmet PMI, LOG, CSP

pyart/correct/region_dealias.py
This is a bugfix for the functionality to use sounding data to fix velocities from region based dealiasing that are off by fixed nyquist velocities. The cost function will now have been determined to reach a minimum once the difference between any region and the reference velocity is less than a nyquist velocity (it was not stopping before this before, causing issues). In addition, the fact that the closest region must be less than one nyquist velocity is now a hard constraint coded in the gradient.
=> FIX: Set minimum for cost function gradient INF norm to be nyquist interval

pyart/aux_io/gamic_hdf5.py
Set the default value of the pulse_width field to None and allow
a GAMIC volume to be loaded even if this field is missing.
=> ENH: GAMIC's volume doesn't mandate a pulse_width field

pyart/aux_io/odim_h5.py
Hi! Here's another pull request from my personal modifications. At the Finnish Meteorological Institute, the radar volumes in ODIM HDF5 format store all elevation scans in the same file, but some of the scans have different amount of range bins and different range resolution. This makes it impossible to read the volumes with pyart without picking the correct scans into separate files first with some external tool. 
So as a workaround, I'm suggesting adding options `include_datasets` and `exclude_datasets` in `pyart.aux_io.read_odim_h5` to select the datasets that are read. The default options select all datasets, so old behaviour is retained.
For example (the volume file is available from [AWS](http://s3-eu-west-1.amazonaws.com/fmi-opendata-radar-volume-hdf5/2021/11/19/fivih/202111190500_f …
=> ADD: Options to select ODIM HDF5 datasets

pyart/aux_io/odim_h5.py
This removes the behavior of overwriting the reflectivity, velocity etc fields with the other due to same field mapping.
=> MNT: Adds for default field names, horizontal and vertical additions.

pyart/graph/gridmapdisplay.py, pyart/graph/radarmapdisplay.py
When parsing a default matplotlib axes for the mapdisplay modules in cartopy 0.19 or higher, a duplicate axes is formed with geoaxes is defined. Removed default defined matplotlib axes as this mapdisplay is utilizing cartopy anyways, so a default geoaxes is defined instead if user provides no projection or axes. Also change of ax.outline_patch to ax.spines['geos'] to removed deprecation warning.
=> FIX: Fixes for overlapping axes in mapdisplay modules.

.github/workflows/build_docs.yml
I noticed after the docs built that the wrong branch name was used in the last step... this fixes that issue so it pushes to the `gh-pages`branch
=> Fix incorrect branch name in action

.github/workflows/build_docs.yml
The docs page is currently blank - it was looking for `dirhtml` instead of `html` this fixes that issue
=> Change which directory docs are in

README.rst, guides/contributors_guide.rst
Now that our docs build using GitHub actions, we can update the old links to that pointed to the `pyart-travis` repo and the `auto-examples`, with the docs built using GitHub actions and examples.
=> Update links to docs/examples

pyart/graph/radardisplay.py
Was a temp fix for np.datetime64 for python3.8, removing this no longer should be an issue and or required.
=> MNT: Removing pandas import and converters.

pyart/retrieve/tests/test_simple_moment_calculations.py
Improve testing suite for `part.retrieve.simple_moment` functionality
=> Add tests for simple moments

examples/README.txt
Closes #1028 
This **should** be the last place in the docs that we need to change the link for
=> Update examples data link to adc

pyart/map/gate_mapper.py, pyart/map/tests/test_gatemapper.py
GateMapper now supports a GateFilter. I've also added some more documentation for GateFilter and also provided a setter for tolerance that will reset the internal KD-Tree if the tolerance variable is changed.
=> ADD: Gatefilter to GateMapper.

doc/source/conf.py
This uses the Google Analytics 4 ID - which won't be replaced in a year
=> Add new google analytics ID

setup.py
Fix for missing registry path. Conda forge and pypi are working correctly, was missing from github repo downloads.
=> MNT: Fix for setup.py registry file.

examples/mapping/compare_two_radars_gatemapper.py
Currently, the plots are not showing up on the [GateMapper example](https://arm-doe.github.io/pyart/examples/mapping/compare_two_radars_gatemapper.html#sphx-glr-examples-mapping-compare-two-radars-gatemapper-py) - this adds in the required `plt.show()` lines
=> Add plt.show()

doc/environment.yml, examples/mapping/plot_compare_two_radars_gatemapper.py
Currently, the GateMapper example is not executing, which is leading to figures not being created. This renames that file, and adds a more restrictive reflectivity filter.
=> Rename Gatemapper Example to Execute

examples/mapping/plot_compare_two_radars_gatemapper.py, pyart/map/gate_mapper.py, pyart/map/tests/test_gatemapper.py
Added a time tolerance to the GateMapper function. Now you can exclude points that are out of synchronization when doing gate to gate comparisons.
=> ADD: Time tolerance to GateMapper

README.rst, guides/contributors_guide.rst
Removes reference of travis and appveyor. Adds new python support and mention of mamba. Closes #1105.
=> DOC: Update to readme and contributors guide

pyart/retrieve/qvp.py
While seeing all available radar tilts for each file is useful, I think it is unnecessary to have it print out every single time. So I have added a bool to the input where you can turn that print statement on-off, but default it is off. Feel free to switch it to default on. I just wanted control to turn it off so my progress bar worked properly.
=> add verbose flag to qvp code

continuous_integration/environment-ci.yml, pyart/io/common.py, requirements.txt
This allows the user to read data both from the local filesystem, and remote sources (ex. AWS), moving the `pyart.io.common` open file module to use `fsspec` instead of the default Python `open`
=> ENH: Use fsspec for io in pyart.io.common to read both local and remote files

doc/environment.yml, doc/source/index.rst, examples/io/README.txt, examples/io/plot_nexrad_data_aws.py, pyart/io/common.py, pyart/io/nexrad_archive.py, pyart/io/nexradl3_read.py, requirements.txt
Here, we add a new example showing how to read NEXRAD Level 2/3 data remotely from AWS
=> ADD: Add AWS NEXRAD example in new IO section

.github/workflows/pypi-release.yml
This PR adds a GitHub action to automate uploading the build to pypi upon a release
=> ENH: Add a pypi release action

.github/workflows/pypi-release.yml, continuous_integration/environment-ci.yml
@mgrover1 I think this should work.
=> MNT: Utilize conda for build due to trmm_rsl.

pyart/util/__init__.py, pyart/util/columnsect.py, pyart/util/tests/test_columnsect.py
Given the lat/lon of the location, return a dictionary containing all radar object fields for the column above the location, as well as, x,y,z gates for the column. Tested with ppi (nexrad) and rhi (csapr) scans.
=> ADD: Utility to subset a radar volume for the column above a location

.github/workflows/ci.yml
Our nightly builds are failing due to GitHub being unable to find the right macOS arm chip builds - this removes that system from our CI
=> FIX: remove macos arm builds

examples/plotting/plot_nexrad_image_muted_reflectivity.py, pyart/graph/tests/test_gridmapdisplay.py
This script provides an example of how to use the `image_mute_radar` function.
=> Add Image muting plotting example to gallery

pyart/graph/gridmapdisplay.py, pyart/graph/radarmapdisplay.py, pyart/graph/radarmapdisplay_basemap.py, pyart/graph/tests/test_radarmapdisplay.py
Pointed out by David Wolff embellish was mispelled, this is a fix for that.
=> MNT: Mispelling of embelish

INSTALL.rst
As pointed out by user srbrodzik, python 3.8 was highest python listed, python 3.9 and 3.10 work for pyart.
=> DOC: Updating docs to represent python versions.

continuous_integration/environment-ci.yml, doc/environment.yml, requirements.txt
It looks like the CI is failing with the new release of numpy, specifically when working with cftime... trying this as a fix
=> FiX: add pinned version of numpy

pyart/graph/gridmapdisplay.py, pyart/graph/radarmapdisplay.py
Catches matplotlib warnings for axes overwrite. Overwriting is done as axes doesn't generate as expected. Suppresses warning until matplotlib creates new axes instance.
=> MNT: Added warning catch for axes.

pyart/retrieve/qpe.py
The variable used in the warning was wrong, as NoneType errors were being created, freq_band_aux was the correct variable.
=> FIX: Str for warning of coefficient band used was wrong.

doc/source/userguide/index.rst
Fix the link to the cookbooks - currently, it's not rendering the link correctly due to a missing `<` symbol
=> FIX: Fix link to cookbooks in user guide

README.rst, pyart/util/radar_utils.py, pyart/util/tests/test_radar_utils.py
Hi dear Py-ART team,
The join_radar function in Py-ART has the problem that it does not merge instrument parameters. This is an issue for certain functions for example _dealias_region_based_, which expects a nyquist_velocity value for every sweep. I think there is currently no way to use this function on a multi sweep scan obtained with join_radar. In our MeteoSwiss version we use the function in this PR, which also merges the most important instrument parameters and is able to merge radar objects which have different variables (by merging only the variables that they have in common).
The code below for example fails for me with the current Py-ART version with error
_nyquist_vel = [radar.get_nyquist_vel(i, check_uniform) for i in 
return(nyq_vel[0])
TypeError: only size-1 arrays can be …
=> FIX: update join_radar to also append instrument parameters

requirements.txt
Remove the restrictive cftime version since they released 1.6.1 and removed the previous 1.6.0 version
=> Remove pinning for specific cftime

pyart/io/uf_write.py
When a radar object originally read in from sigmet file generated by IRIS is written to UF using `pyart.io.write_uf`, the range_start_m and range_step vars are single-object arrays. When these are subsequently rounded to integers by `round()`, the arrays give a traceback.
I fixed this by checking to see if these values were arrays, and if so, accessing the first value of these arrays. There may be a better implementation for fixing this, I'm not sure. I've attached an example IRIS sigmet file here (unzip the file first): [ADR220322013706.zip](https://github.com/ARM-DOE/pyart/files/9172328/ADR220322013706.zip)
=> fix writing IRIS sigmet files to UF

pyart/util/radar_utils.py
In the current version of py-ART, joining two radar files using `pyart.util.join_radar(rdr1, rdr2)` produces a radar object that contains PRT data only from `rdr1`. 
This commit appends the PRT data from `rdr2`
This is necessary because if the joined radar object is then exported to universal format using `pyart.io.write_uf`, the rays from the second radar object don't have PRT data, causing an out-of-bounds array traceback.
=> FIX: join_radar also joins pulse repititon times iparam

.github/workflows/ci.yml, pyart/util/__init__.py, pyart/util/radar_utils.py, tests/util/test_radar_utils.py
Dear Py-ART team,
In this PR I propose the addition of a ~~cut_radar~~ subset_radar function from our MeteoSwiss fork of the library (thanks @jfigui). It cuts a radar object to a new domain specified by bounds in range, azimuth and elevation, and returns a new object. It can be useful to make processing faster when one is interested only in a certain subdomain around the radar (typically shorter ranges and only a certain sector).
This function is used a lot in our [pyrad](https://github.com/MeteoSwiss/pyrad) library, which is  a framework for real time radar processing that relies on PyART. 
I also added a short test function that checks if a cut radar object has indeed coordinates that match with the specified bounds.
Cheers,
Daniel W.
=> ADD: addition of subset_radar function in radar_utils

continuous_integration/environment-ci.yml, doc/environment.yml
With the recent release of Shapely (1.8.3), there are some errors popping up in Cartopy (see [#2067](https://github.com/SciTools/cartopy/issues/2067)).
We need to pin the previous version of shapely until this issue is resolved.
=> FIX: Pin previous version of shapely

pyart/graph/radarmapdisplay.py
Currently, when you create a plot using the GridMapDisplay, the plot returns the following error
```python
/ccsopen/home/mgrover/mgrover/sail-radar-dev/lib/python3.9/site-packages/cartopy/mpl/gridliner.py:451: UserWarning: The .xlabels_top attribute is deprecated. Please use .top_labels to toggle visibility instead.
warnings.warn('The .xlabels_top attribute is deprecated. Please '
/ccsopen/home/mgrover/mgrover/sail-radar-dev/lib/python3.9/site-packages/cartopy/mpl/gridliner.py:487: UserWarning: The .ylabels_right attribute is deprecated. Please use .right_labels to toggle visibility instead.
warnings.warn('The .ylabels_right attribute is deprecated. Please '
```
This solves that issue by using the new, suggested methods
=> FIX: Use new api to toggle top and right labels

examples/correct/plot_dealias.py, examples/plotting/plot_choose_a_colormap.py
We need to remove the reference to the FourDD algorithm here - this fixes that typo
=> Fix title of dealias example

pyart/graph/gridmapdisplay.py, pyart/graph/radarmapdisplay.py
Closes #1297.
Added keyword add_lines in plot_grid in gridmapdisplay.py and plot_ppi_map in radarmapdisplay.py.
General linting of gridmapdisplay and radarmapdisplay.
=> Plot grid modif

pyart/correct/phase_proc.py
The phase processing code is throwing deprecation warnings for using scipy.ndimage.filters.convolve1d. It looks like that function is moving to scipy.ndimage.convolve1d. This fix would take care of the deprecation warning.
=> FIX: Phase processing code throwing deprecation warnings for scipy.ndimage.filters.convolve1d

continuous_integration/environment-ci.yml, doc/environment.yml, examples/retrieve/plot_hydrometeor.py, examples/retrieve/plot_vad.py
Closes #1260 
Dear pyart team,
Sorry for the long delay, I had to wait for the green light to share some of the data and had some fieldwork to do...
Here are two new examples for the pyart gallery taken from the erad2022 open radar course.
**plot_vad.py:**
Compute VAD for every sweep of a volumetric scan, compute a vertical profile of U and V wind components, display the results
**plot_hydrometeors.py:**
Compute attenuation and KDP, read temperature from another source and add it to radar object, compute hydrometeors, display the results on a PPI plot with a categorical colorbar
It requires three files to be acquired with the *get_test_data* method. I hosted the files [here ](https://www.swisstransfer.com/d/7d632b77-c120-4316-be80-13a3a750aca6). Could you please put them on …
=> DOC: Added two pyart examples (VAD and hydrometeors)

pyart/core/radar.py, tests/core/test_radar.py
This function applies a filter to fields and either replaces or adds new filtered fields.
Note, adding tests to this PR, just initial review.
Closes, #763
=> ADD: Adding add_filter function to radar.py.

.github/workflows/ci.yml, .github/workflows/wheels.yml, continuous_integration/environment-ci.yml, doc/environment.yml
Since Python 3.11 is now released, we should support this new Python version. Adding to CI/wheels.
=> Add ci for Python 3.11

pyart/aux_io/gamicfile.py
solves #1336 
But only if range resolution is same for all sweeps.
=> FIX: use max_num_gates for calculation of data shape

pyart/aux_io/gamic_hdf5.py, pyart/aux_io/gamicfile.py
=> FIX: check uniformity of range_step, get consistent range_step for gamic reader

setup.py
Need to look into the difference more on find_namespace_packages and find_packages. Trying to avoid similar install error behavior as seen in ACT.  I switched to avoid warnings during the feedstock testing.
=> MNT: Revert setuptools, to avoid unwanted behavior.

examples/io/read_older_nexrad_data_aws.py
This shows how to fix missing lat and lon metadata.
Closes #1354
=> DOC: Adding an example on how to read older nexrad data.

.github/workflows/wheels.yml
just noticed that the latest versions didn't include 311 wheels, despite #1303
This should fix it for next time.
=> REL: fix build for Python 3.11 wheels

README.rst
Fix the link to the old travis docs in the readme
=> FIX: Fix a link to the old docs in the readme

.github/workflows/ci.yml
They have started dropping support for Python 3.8 over in Xarray (https://github.com/pydata/xarray/pull/7461) and since xarray is a dependency, as well as other xarray-related packages, we should drop support in the tests for this.
=> Drop Support for Python 3.8 in CI

doc/source/userguide/contributors_guide.rst
Not sure I built this correctly, but a fix to a broken doc link to the examples
=> BUG: Fix to broken doc link

pyart/core/grid.py, pyart/graph/gridmapdisplay.py, tests/core/test_grid.py, tests/graph/test_gridmapdisplay.py
Closes #1389 
This ensures we use 2D latitude/longitude for the `to_xarray()` method for grids.
=> FIX: Fix wrong coordinate configuration for xarray

README.rst
Use the Open Radar community link for the mailing list.
=> Update link to mailing list

pyart/__init__.py, pyart/testing/example_data.py, setup.py
`pkg_resources` is deprecated https://setuptools.pypa.io/en/latest/history.html#v67-5-0
Note to reviewers: it's not perfectly clear to me which versions of Python are still supported as various sources differ:
- from PyPI classifiers: 3.6-3.10
- from 1.14.5 wheels: 3.8-3.11
- from test matrix: 3.9-3.11
Are the classifiers are just out of date ? I did the maximal effort to keep compatibility with Python<3.8 here, but if 3.9 is already the minimal supported version this PR can be simplified.
=> drop pkg_resources as a runtime requirement

pyart/graph/radarmapdisplay.py, pyart/graph/radarmapdisplay_basemap.py
Adds `colorbar_orient` as an option to `pyart.graph.RadarMapDisplay.plot_ppi_map()` and `pyart.graph.RadarMapDisplayBasemap.plot_ppi_map()`.
Documentation changed to reflect this in as far as adding bits in the function docstrings, I don't know if any more than that is needed.
=> colorbar_orient option to plot_ppi_map functions

pyart/core/radar.py, pyart/io/cfradial.py, pyart/lazydict.py
Fixes the failing CI caused by updates to ruff
=> FIX: Fix new linting issues

pyart/map/gate_mapper.py, tests/map/test_gatemapper.py
GateMapper would throw an error if a source field was being mapped onto the destination radar if the field existed in the source radar but not the destination. This made it hard to map the beam blockage flag onto the cmac radar object. 
I've added a test for this and reworked the test to make more sense (old and new were backwards).
=> FIX: GateMapper will now map source field to destination radar even if field not in destination radar

pyart/aux_io/odim_h5.py
=> FIX: Fix type of time for odim reader

.github/workflows/build_docs.yml, continuous_integration/environment-ci.yml, doc/environment.yml, doc/source/conf.py, doc/source/index.rst, pyart/retrieve/comp_z.py, requirements.txt
=> MNT: Remove pandas pinning, testing.

examples/retrieve/plot_convective_stratiform.py, pyart/graph/convstrat_scheme_plot.py, pyart/retrieve/_echo_class.py
Hi folks,
I found a minor error with my initial code which masked the final convective-stratiform array by the background field instead of the field itself. There were also a minor format issue in one of the functions and some minor issues related to the plotting in the example (which I hope I have fixed). 
Hopefully this is a straightforward edit.
Best,
Laura
=> Minor adjustments to convective-stratiform algorith, documentation, and example

pyart/aux_io/sinarame_h5.py, pyart/graph/common.py, pyart/retrieve/kdp_proc.py
Fix linting errors failing due to recent updates to ruff
=> Fix linting errors

pyart/aux_io/sinarame_h5.py, pyart/graph/radardisplay.py, pyart/io/cfradial.py, tests/io/test_cfradial.py
Add isinstance checks and fix other linting errors occurring in the CI system
=> FIX: Add isinstance checks to improve linting

doc/environment.yml, examples/xradar/README.txt, examples/xradar/plot_xradar.py, pyart/xradar/accessor.py, tests/xradar/test_accessor.py
Add a PPI plotting example using Py-ART and xradar together
=> DOC: Add docs for using xradar and Py-ART together

examples/xradar/plot_grid_xradar.py
Fix the typo in the title of the xradar gridding example
=> FIX: Fix the small typo in xradar grid example

.github/workflows/ci.yml, .github/workflows/wheels.yml, README.rst, doc/source/index.rst
Add testing and wheels for python 3.12
=> ADD: Add python 3.12 to ci and wheels

examples/xradar/plot_grid_xradar.py, examples/xradar/plot_xradar.py
Fix the colormaps used in the xradar suite of examples
=> FIX: Fix the colormap in xradar examples

doc/source/changelog.md
Add the updated changelog for the latest release
=> DOC: Add updated changelog for new release

.github/workflows/ci.yml, continuous_integration/environment-ci.yml
Makes sure python versions are working as expected in the CI system
=> FIX: Fix python version used in CI system

pyart/xradar/__init__.py, pyart/xradar/accessor.py, tests/xradar/test_accessor.py
I have added a feature to convert an xarray object to a PyART Grid, essentially doing the reverse of what .to_xarray() does. This will help switching between PyART/Xarray grids more seamlessly.
=> ADD: Ability to create a Py-ART Grid FROM an xarray object

.github/workflows/ci.yml, continuous_integration/environment-ci.yml, pyart/io/cfradial.py
This fixes reading in the scan_mode when the scan_name is an empty string
=> FIX: Fix setting scan_mode when scan_name is empty

continuous_integration/environment-ci.yml, doc/environment.yml
Until #1500 is resolved, let's pin to the non-latest release of MetPy for the doc/CI system. Once the upstream issue is resolved, we can remove these pins.
=> FIX: Fix failing CI by pinning older metpy versions

doc/environment.yml, doc/source/conf.py, examples/retrieve/plot_convective_stratiform.py, examples/retrieve/plot_feature_detection.py, examples/retrieve/plot_hydrometeor.py
Fix the failing gallery build by updating examples + pinning one version earlier sphinx
=> FIX: Fix the failing build of the gallery

CONTRIBUTING.rst
Update the doc section to show users how to use pre-commit hooks.
=> DOC: Add pre-commit section to docs

continuous_integration/environment-ci.yml, doc/environment.yml
Remove the pin for metpy versions, which was added there to resolve issues with the cross section functionality.
=> FIX: Remove the metpy pin for doc build and CI

.github/workflows/wheels.yml
Fix the usage of the new upload/download artifact action
=> FIX: Fix the name of download-upload-artifact action

continuous_integration/environment-ci.yml, doc/environment.yml, environment.yml, pyart/io/nexrad_level3.py, requirements.txt
Add in xdrlib lightweight replacement, using mda-xdrlib
=> ADD: Add new xdrlib drop in replacement

.github/workflows/wheels.yml, pyart/retrieve/echo_class.py
When each os wheels zip is created, they are stored with macos.zip etc etc. I'm wondering if its having a hard time finding the wheels within each. I looked up some docs and looks like if there is multiple artifacts, might be able to download from each. Might be a solution...
=> FIX: Possible fix for upload failure for wheels.

pyart/util/columnsect.py
Instead of using the units attribute separately, use the existing utility in Py-ART that deals with this more robustly
=> FIX: Use existing time extraction in Py-ART in columnsect

pyart/util/radar_utils.py
=> FIX: consistent sweep determination for RHI at 0 degrees azimuth

examples/mapping/plot_grid_single_sweep_ppi.py, pyart/map/_gate_to_grid_map.pyx, pyart/map/gates_to_grid.py, tests/map/test_gates_to_grid.py, tests/map/test_grid_mapper.py
The gridding and default RoI methods always had a Cartesian Z component weighting factor. Here, optional weighting factors for the gridding routine are added. This enhancement provides the basis for separately gridding single RHI sweeps, which will become highly useful once the radar implementation is finalized.
The code edits were tested against some data, including [existing examples](https://arm-doe.github.io/pyart/examples/mapping/plot_grid_single_sweep_ppi.html#sphx-glr-examples-mapping-plot-grid-single-sweep-ppi-py) and showed robust behavior that does not impact the default behavior.
Two related test scripts and the above-mentioned example were updated to reflect code changes.
=> ENH: Dimension-dependent weighting factor flexibility in gridding

examples/mapping/plot_grid_single_sweep_ppi.py, pyart/map/_gate_to_grid_map.pyx, pyart/map/gates_to_grid.py, pyart/map/grid_mapper.py, tests/map/test_gates_to_grid.py, tests/map/test_grid_mapper.py, tests/xradar/test_accessor.py
This updated PR now includes ARM-specific min_radius option (automatically determined) to retain high-resolution information when operating on standard ARM radar data.
=> FIX: physically consistent RoI calculation for gridding; updated gridding input parameters to mitigate smearing

pyart/retrieve/echo_class.py
=> ENH:Docs:hydroclass

pyart/core/grid.py, tests/core/test_grid.py
=> MNT: Update to_xarray to show nradar info.

pyart/io/cfradial.py
@mgrover1 My thought process for this was to have the arm_scan_name as an optional parameter as sweep_mode (from what im seeing in the cfradial document) contains the information we should be using by default. I'm leaving the option for arm_scan_name if the scan type is stored there instead. Idk if this is the best way forward for this? But figured I'd post the idea here.
=> MNT: Update arm_scan_name to be optional. Also dep warning fix.

pyart/filters/gatefilter.py, tests/filters/test_gatefilter.py
This is useful for removing artificial rings near the end of data. Closes #407
=> ADD: Adding new gatefilter method to remove last gates.

pyart/util/columnsect.py
Similar to `get_field_location`, definition of the start of the radar volume updated to use the utility `datetime_from_radar`
=> BUG: Update to Column Vertical Profile Handling of Defining Radar Basetime

pyart/core/grid.py, tests/core/test_grid.py
=> FIX: Update pyproj functions to take string.

pyart/default_config.py, pyart/io/nexrad_level3.py
Initial PR might need to be updated more.
=> ENH: Update nexrad level 3 reader to read super resolution data.

pyart/retrieve/comp_z.py, tests/retrieve/test_comp_z.py
Fix the deprecated interp2d in composite z calculation
=> FIX: Fix builds for latest scipy

pyart/retrieve/echo_class.py
1.  Included details of the output dict. Added names of the 9 hydrometeor classes that the function identifies.
2. Added code example.
=> Updated Documentation for retrieve/hydroclass_semisupervised function

pyart/retrieve/qpe.py, pyart/retrieve/simple_moment_calculations.py
Add additional references currently missing in the docs
=> Add more references

examples/xradar/plot_dealias_xradar.py, examples/xradar/plot_grid_xradar.py, examples/xradar/plot_xradar.py, pyart/xradar/accessor.py, tests/xradar/test_accessor.py
Add a to_radar() method to xradar using the accessor interface.
=> ADD: Add to_radar() method to xradar objects

.readthedocs.yaml
Enable readthedocs by adding a configuration file
=> DOC: Enable readthedocs

pyart/correct/__init__.py, pyart/correct/bias_and_noise.py, tests/correct/test_correct_bias.py
Adds new cloud mask functions to Py-ART from radtraq.
=> ADD: Adding cloud mask code.

README.rst, pyart/graph/gridmapdisplay.py, requirements.txt, tests/graph/test_gridmapdisplay.py, tests/graph/test_plot_maxcappi.py
Add cartopy as a dependency for Py-ART
=> ADD: Add cartopy as a dependency

examples/plotting/plot_corner_reflector.py
Add a corner reflector example
=> ADD: Add corner reflector example

pyart/graph/max_cappi.py
This fix addresses an issue in the plot_maxcappi function where radar_name could appear either as a list of byte strings or a simple string.
=> FIX: Minor fix in plot_maxcappi

pyart/xradar/accessor.py
This is a minor fix to PyART's wrapper around the xradar object to correctly determine the fixed_angle attribute. The current version caused the fixed_angle attribute to be reindexed along the number of rays, but this attribute is one entry per sweep. This patch fixes that.
=> FIX: Fixed angle incorrect in xradar PyART radar object wrapper

examples/plotting/plot_cappi.py, pyart/retrieve/__init__.py, pyart/retrieve/cappi.py, tests/retrieve/test_cappi.py
This PR introduces a new feature to generate a Constant Altitude Plan Position Indicator (CAPPI) from radar data directly within Py-ART. The new `create_cappi` function allows users to specify the altitude and radar fields for CAPPI generation, simplifying the process and making it more accessible.
The implementation draws on existing work, with valuable insights from the `comp_z.py` module by @dopplerchase and @vlouf's [CAPPI notebook](https://github.com/vlouf/radar_cappi/blob/master/CAPPI.ipynb). This addition integrates and builds on these concepts, providing a streamlined way to create CAPPI products within Py-ART.
```python
import pyart
import matplotlib.pyplot as plt
from open_radar_data import DATASETS
file = DATASETS.fetch("RAW_NA_000_125_20080411190016")
radar = …
```
=> ADD: Create CAPPI from Radar

examples/plotting/plot_cappi.py, examples/plotting/plot_max_cappi.py, pyart/graph/max_cappi.py
=> FIX: Fix errors in docstrings and comments in CAPPI and MAX_CAPPI

pyart/map/gates_to_grid.py, pyart/map/grid_mapper.py, pyart/retrieve/kdp_proc.py, pyart/util/radar_utils.py, tests/core/test_grid.py
I fixed this by calling .items() to pull from the array. Also checks, similar to radar utils, if the arrays are 1 or more (mobile radar).
=> FIX: Updates code to fix scalar warnings.

.github/workflows/build_docs.yml, .github/workflows/ci.yml, continuous_integration/environment-ci.yml, doc/environment.yml, requirements.txt
Fix incompatibility with xradar/xarray releases
=> FIX: Fix pinning of xradar and xarray

.github/workflows/ci.yml, continuous_integration/environment-ci.yml, doc/environment.yml, pyart/xradar/accessor.py, requirements.txt
xarray-datatree has been merged to xarray>=2024.10.0. Since xarray version is not pinned, this will cause ImportErrors unless addressed. This is PR is an attempt towards a phased transition to using `xarray.datatree`.
=> FIX: Ensure backwards compatibility with datatree/new versions of xarray

pyart/_debug_info.py, pyart/aux_io/gamicfile.py, pyart/core/radar.py, pyart/correct/phase_proc.py, pyart/correct/region_dealias.py, pyart/graph/common.py, pyart/io/common.py, pyart/io/mdv_common.py, pyart/io/nexrad_level3.py, pyart/io/rsl.py, pyart/retrieve/spectra_calculations.py, pyart/testing/data/make_small_mdv_ppi.py, pyart/testing/data/make_small_mdv_rhi.py, pyart/xradar/accessor.py
Removed glpk version check as well as it wasn't doing anything, can be replaced by pyglpk once there is a working version.
=> FIX: Update to use f-format strings. Remove glpk version check until we have a working version

doc/source/conf.py, examples/io/plot_read_cfradial2.py, pyart/xradar/accessor.py, tests/xradar/test_accessor.py
Add a cfradial2 example and associated improvements
=> DOC: Add cfradial2 read example

pyart/aux_io/__init__.py, pyart/aux_io/arm_vpt.py
A method to robustly read ARM MMCR b1-level data files (the datastream available through the ARM Archive).
The method returns a `dict` with keys representing each of the operated MMCR modes (available in the data files) and values representing the corresponding `Radar` objects. An optional input parameter (`mode_to_extract`) enables only extracting a single mode, in which case a single `Radar` object is returned.
The method is written in a similar format to the `read_kazr` method (which has some clutter in it) under the same `aux_io` module.
That module lacks unit tests (as also noted in its `__init__.py` script) and therefore I didn't include unit tests.
- [ x] Documentation reflects changes
=> ENH: `read_mmcr` method to read ARM MMCR b1-level data files

pyart/xradar/accessor.py, tests/xradar/test_accessor.py
Ensure the accessor has access to the lat/lon/alt values
=> ADD: Add get_gate_lat_lon_alt to pyart/xradar object

.github/workflows/ci.yml, INSTALL.rst, README.rst, doc/source/index.rst, environment.yml
CI: Update ci to use python 3.13, 3.12 and 3.11. CI should work as it now does for the Py-ART conda-forge recipe. Also updated docs to remove google groups
=> CI: Update ci to use python 3.13, 3.12 and 3.11.

pyart/xradar/accessor.py, tests/xradar/test_accessor.py
Fix the remaining bugs with gridding xradar objects
=> ADD: Add gridding ability to xradar radar object

.github/workflows/ci.yml
Should be able to use pip installations in the environment yml file again if need be.
=> CI: Remove mamba 2.0 pin as pip install issues are resolved in 2.0.4.

pyart/io/nexrad_common.py
- Add KHDC (Hammond, LA) radar station to `io/nexrad_common.py` with coordinates lat: 30.519, lon: -90.407, elev: 43 ft
- Include documentation noting KHDC metadata source from NWS notification document
- KHDC not yet available in NOAA HOMR database as of 8/21/25
Reference: https://www.weather.gov/media/notification/pdf_2023_24/scn24-11_khdc_nexrad_level_iii_product_dissemination.pdf
=> feat(nexrad): add KHDC radar station to NEXRAD_LOCATIONS

pyart/aux_io/rainbow_wrl.py
**Problem:**
When reading RHI .ele files, the following error occurs if the file contains only one slice (nslices == 1 → single_slice = True):
UnboundLocalError: local variable 'nbins_sweep' referenced before assignment
The issue originates from the logic in pyart/aux_io/rainbow_wrl.py.
In the single_slice branch, nbins_sweep is never defined, but it is later referenced here:
fdata[ssri[i] : seri[i] + 1, :] = _get_data(
slice_info["slicedata"]["rawdata"],
rays_per_sweep[i],
nbins_sweep[i],   # this remains undefined when single_slice == True
maxbin,
)
**Cause:**
For RHI .ele files from IITM Radar (India), single-slice volumes are common. Since nbins_sweep is only created inside the else branch (multi-slice), it fails in single-slice cases.
**Fix:**
When single_slice == True, explicitly …
=> Fix RHI (.ele) file reader bug in rainbow_wrl.py (nbins_sweep undefined in single-slice case)
