ARM-DOE/pyart

pyart/aux_io/gamic_hdf5.py

pyart.aux_io.read_gamic will now read mvol GAMIC files.

MAINT: Improved GAMIC reading.

---

pyart/core/radar.py
pyart/correct/__init__.py
pyart/correct/filters.py
pyart/correct/tests/test_filter.py

Add a GateFilter class in the pyart.correct namespace which is intended to be used for creating boolean array for selecting gates for processing.

ENH: GateFilter class

---

pyart/correct/_fast_edge_finder.c
pyart/correct/_fast_edge_finder.pyx

nvel is determined from valid indices whenever neighbor is determined.

BUG: Fixed bug which causes segmentation fault in dealias_region_based.

---

doc/source/dev_reference/io.rst
pyart/correct/region_dealias.py
pyart/io/auto_read.py
pyart/io/cfradial.py
pyart/io/lazydict.py
pyart/io/nexrad_archive.py
pyart/io/rsl.py
pyart/io/tests/test_auto_read.py
pyart/io/tests/test_cfradial.py
pyart/io/tests/test_nexrad_archive.py
pyart/io/tests/test_rsl.py

Add support for delayed loading of field data from radar files in multiple formats.

ENH: Delayed loading of field data from radar files.

---

pyart/aux_io/__init__.py
pyart/aux_io/d3r_gcpex_nc.py

This version of the code, placed in aux_io, reads the raw Ku and Ka netCDF files for the
GCPEx field campaign.  My understanding is that the D3R format has been
under revision and may be different field campaigns, but I have tested
for GCPEx and it seems to work.  Comments/improvements welcome.

Initial version of CSU D3R radar reader

---

pyart/io/grid_io.py

Substantial alteration in writing and reading grid, I believe this should still work with ARM-standards at the same time it can write and read more/different variables (including latitude and longitude of pull request #264). This however need much more discussion.

alteration in grid_io 

---

pyart/io/cfradial.py

BUG: Better handling of scalar NetCDF variables across netCDF versions

---

pyart/io/_sigmetfile.c
pyart/io/_sigmetfile.pyx
pyart/io/tests/test_sigmet.py

Fixed issue reading sigmet 1byte datatype files. Added test.

---

.travis.yml
continuous_integration/install.sh

TST: Container-based Travis CI setup

---

examples/plotting/plot_ppi_mdv.py
examples/plotting/plot_rhi_cfradial.py
examples/plotting/plot_rhi_mdv.py
examples/plotting/plot_rhi_sigmet.py
pyart/graph/plot_cfradial.py
pyart/graph/plot_mdv.py
pyart/graph/plot_rsl.py

Deprecate the MdvDisplay, RslDisplay and CFRadialDisplay classes.

MAINT: Deprecate file specific displays

---

doc/source/dev_reference/aux_io.rst
pyart/aux_io/gamic_hdf5.py
pyart/aux_io/gamicfile.py

Refactored gamic_hdf5 module moving all direct access to the HDF5 file
to the GAMICFile class.

MAINT: Refactor gamic_hdf5 module

---

pyart/correct/region_dealias.py

Fixes for small bugs which effect corner cases of the dealias_region_based function.

BUG: Various fixes for bugs in the region_dealias module

---

continuous_integration/install.sh

Current version of TRMM RSL is 1.48

MAINT: Have Travis-CI use latest version of TRMM RSL on binstar.org

---

pyart/graph/common.py
pyart/graph/gridmapdisplay.py
pyart/graph/radardisplay.py
pyart/graph/radardisplay_airborne.py
pyart/graph/radarmapdisplay.py
pyart/graph/tests/test_radar_display.py

In the spirit of issue #248; to help a little in artview and in anticipation of improving `GridDisplay`, I made some independent methods based in what is being done in  `RadarDisplay`. I would just like to get an approval before applying to `RadarDisplay` (removing some private methods and redirecting public ones)
Also, do you have any suggestion on how to proceed (define names and stuff) while creating similar ones for grid?

externalise methods from display

---

pyart/graph/common.py
pyart/graph/gridmapdisplay.py
pyart/graph/radardisplay.py
pyart/graph/radardisplay_airborne.py
pyart/graph/radarmapdisplay.py
pyart/graph/tests/test_gridmapdisplay.py

Several additions to gridmapdisplay, making it more similar to radardisplay. I'm not sure how some things here will be received, so while revising this keep in mind my last comment to issue  #294.
Also check pyart example `plot_grid_three_panel.py` for eventual bugs

ENH: add label, title etc. to gridmapdisplay

---

pyart/graph/gridmapdisplay.py
pyart/graph/radardisplay.py
pyart/graph/radardisplay_airborne.py
pyart/graph/radarmapdisplay.py

MAINT: Change default value of mask_outside to False

---

pyart/io/_sigmetfile.c
pyart/io/_sigmetfile.pyx

BUG: 1-byte width field from Sigmet files returns in m/s

---

pyart/graph/radardisplay_airborne.py

BUG: Missing gatefiter parameter in plot_sweep_grid

---

doc/source/dev_reference/util.rst
examples/plotting/plot_xsect.py
pyart/util/__init__.py
pyart/util/tests/test_xsect.py
pyart/util/xsect.py

cross_section_ppi extracts azimuthal cross sections from a volume of PPI
scans.

ENH: Add pyart.util.cross_section_ppi function

---

continuous_integration/install.sh
doc/source/dev_reference/io.rst
pyart/config.py
pyart/default_config.py
pyart/io/__init__.py
pyart/io/tests/test_uf_write.py
pyart/io/uf_write.py
pyart/io/uffile.py

Add a `pyart.io.write_uf` function for writing UF files from **Radar** instances.

ENH: write UF files

---

pyart/io/chl.py

Just removed some documentation artifacts from the mdv reader this was based on.

Update chl.py documentation

---

pyart/io/mdv_common.py
pyart/io/uf_write.py

See GitHub discussion of commit 26c6cb1f for details.

BUG: struct.pack requires native string on Python < 2.7.7

---

pyart/core/__init__.py
pyart/core/radar.py

Enabled join_radar in __init__.py

Update join_radar function.

---

pyart/io/sigmet.py
pyart/util/__init__.py
pyart/util/circular_stats.py
pyart/util/tests/test_circular_stats.py

Calculate the pointing angles (azimuth and elevation) using a circular mean between the starting and ending angles.

Circular means in Sigmet pointing angles

---

.coveragerc
pyart/tests/test_debug_info.py

Add and modify unit tests to provide improved code coverage

TST: Additional code coverage in unit tests

---

doc/source/dev_reference/index.rst
doc/source/user_reference/index.rst

Changed documentation to reflect suggested text. PR only includes commits related to the Doc update.
Updated Text:
#412 Introduction to Developer Reference.
#413 Introduction to The User Reference documentation.

Updates to resolve outstanding issues #412 and #413

---

.travis.yml
README.rst
appveyor.yml
continuous_integration/appveyor/run_with_env.cmd
continuous_integration/install.sh

MAINT: Remove support for Python 2.6 and 3.3, add Python 3.5

---

continuous_integration/install.sh

TST: Use system libgfortran on Travis CI

---

doc/sphinxext/gen_rst.py
doc/sphinxext/numpydoc/comment_eater.py
doc/sphinxext/numpydoc/compiler_unparse.py
doc/sphinxext/numpydoc/docscrape.py
doc/sphinxext/numpydoc/docscrape_sphinx.py
doc/sphinxext/numpydoc/numpydoc.py
doc/sphinxext/numpydoc/tests/test_docscrape.py
doc/sphinxext/numpydoc/tests/test_phantom_import.py
doc/sphinxext/numpydoc/tests/test_plot_directive.py
doc/sphinxext/numpydoc/tests/test_traitsdoc.py
doc/sphinxext/numpydoc/traitsdoc.py
examples/correct/plot_attenuation.py
examples/correct/plot_dealias.py
examples/correct/plot_lp_phase_proc.py
examples/mapping/plot_map_one_radar_to_grid.py
examples/mapping/plot_map_two_radars_to_grid.py
examples/plotting/plot_grid_three_panel.py
examples/plotting/plot_nexrad_reflectivity.py
examples/plotting/plot_ppi_basemap_with_rings.py
examples/plotting/plot_ppi_sigmet.py
examples/plotting/plot_rhi_cfradial.py
examples/plotting/plot_rhi_contours_differential_reflectivity.py
examples/plotting/plot_rhi_data_overlay.py
examples/plotting/plot_rhi_mdv.py
examples/plotting/plot_rhi_sigmet.py
examples/plotting/plot_rhi_two_panel.py
pyart/core/transforms.py

Testing to see if Pull Request Trigger CI

---

pyart/io/cfradial.py

NetCDF4 1.2.3+ returns a MaskedConstant for masked scalar variables. When
reading file which contain this data this is converted into a 1D array
containing a single masked entry.

BUG: Fix NetCDF4 1.2.3+ masked constant issue

---

pyart/aux_io/odim_h5.py

Support for reading ODIM SCAN and ELEV (RHI) objects.

MAINT: ODIM_H5 improvements

---

continuous_integration/install.sh
pyart/io/tests/test_cfradial.py

TST: Test only non-locale dependent time string

---

continuous_integration/install.sh
pyart/io/tests/test_uf.py
pyart/io/uf.py

Thanks to Dustin on the Py-ART mailing list for reporting this bug.

Sweep mode fix for UF files

---

pyart/aux_io/gamic_hdf5.py
pyart/aux_io/gamicfile.py
pyart/default_config.py

This fixes the `pulse_width_us` vs `pulse_width_mks` described in #534

FIX: several fixes for pyart.aux_io.read_gamic()

---

pyart/aux_io/odim_h5.py

ENH: Support for reading ODIM H5 AZIM files

---

pyart/util/radar_utils.py

Changed based upon update from Jordi Figueras i Ventura

MAINT: Clean up join_radar function

---

pyart/io/nexrad_level2.py

Read in NEXRAD level 2 files which contain Channel Terminal Manager (CTM)
information in what is now the compression record.
closes #552

BUG: Read NEXRAD L2 files with CTM information

---

pyart/aux_io/__init__.py
pyart/aux_io/rainbow_wrl.py

Dear py-art users,
I would like to add a function to read rainbow files for Py-ART using the wradlib library.
It is contained in file rainbow_wrl.py in module aux_io.
Let me know if it is up to standard or I should change something.
Jordi

Added rainbow_wrl.py. Function to read rainbow5 files

---

index.html

With the publication of the JORS paper and the need for citations I updated the
index.html in the gh-pages to encourage people to cite.
Fixed a typo while I was at it

ADD: Updated index.html with citation

---

doc/source/dev_reference/util.rst
pyart/default_config.py
pyart/util/__init__.py
pyart/util/simulated_vel.py
pyart/util/tests/test_simulated_vel.py

Add the `simulated_vel_from_profile` function to the pyart.util namespace.
This function creates a simulated radial velocity field from a profile of
horizontal winds.

ENH: Simulated radial velocities from a profile

---

pyart/aux_io/gamic_hdf5.py

Decode strings read from GAMIC HDF5 files assuming a UTF-8 encoding.
closes #581

BUG: Decode strings from GAMIC files

---

README.rst

Update README.rst with new conda channel and package name in section of
installing Py-ART.

DOC: Update README.rst with new conda info

---

pyart/retrieve/__init__.py
pyart/retrieve/echo_class.py
pyart/retrieve/qpe.py

Dear Py-ART users,
I am submitting for your consideration:
- An hydrometeor classification algorithm in retrieve/hydroclass_semisupervised
- Various rainfall rate estimators: Z-R, A-R, KDP-R, Z-R with a polynomial relation, blended Z-R A-R, blended Z-R, KDP-R and a rainfall rate based on the results of the semisupervised classification.
Let me know if it is up for standard.
Jordi

hydrometeor classification and QPE

---

pyart/aux_io/sinarame_h5.py

Just an update to reflect the changes made in `odim_h5` reader.
Closes the enhancement proposal in #600

Updated sinarame_h5 reader

---

pyart/aux_io/__init__.py
pyart/aux_io/sinarame_h5.py

I believe I didn't forget anything for the dev documentation. Let me know if something's wrong with the addition.
This fully closes #600.

Added a CfRadial writer for SINARAME H5 files

---

pyart/graph/common.py
pyart/graph/tests/test_common.py

FIX: Bug swapping az for ele in plot_ray

---

INSTALL.rst

* Update supported Python versions
* Remove minimum versions from other packages
* Update URL for netcdf4-python

DOC: Update INSTALL.rst file

---

pyart/__init__.py

Adds an Acknowledgement request for users. This acknowledgement will allow DoE to track usage in publications.

ADD: Add DoE acknowledgement to __init__.py

---

pyart/filters/gatefilter.py

BUG: Add missing import to gatefilter module

---

contributors_guide.rst

Pull request for the contributor's guide. In early stage, and will be changed based on suggestions, etc.

Contributor guide

---

contributors_guide.rst

Minor changes, and typos. Add information to recommend git checkout -b from master branch and not changed branches. git merge upstream master should have been git merge upstream/master.

DOC: Contr guide updates

---

pyart/filters/__init__.py
pyart/filters/gatefilter.py
pyart/filters/tests/test_gatefilter.py
pyart/retrieve/__init__.py
pyart/retrieve/simple_moment_calculations.py
pyart/retrieve/tests/test_simple_moment_calculations.py

calculate_velocity_texture is moved to pyart.retrieve.

MAINT: Move calculate_velocity_texture to pyart.retreive

---

pyart/aux_io/arm_vpt.py

iteritems no longer supported for dict in Python 3.. simple fix

FIX: Python 3 issue with KAZR ingest

---

pyart/io/nexrad_level2.py

changed all fromstring() to frombuffer() due to deprecation warnings in numpy

changed all fromstring() to frombuffer() due to deprecation warnings in numpy 

---

pyart/correct/region_dealias.py

This is the new version of the dealiasing code that includes the option to minimize the difference between the folded regions and a sounding for certain scans that the region based dealiasing algorithm overcorrects.

EDIT: Adding new version of dealiasing code

---

pyart/retrieve/kdp_proc.py
pyart/util/__init__.py

Dear Py-ART comunity,
As promised I make a pull request with a fix of the KDP/PhiDP retrieval from Vulpiani.
Jordi

Bug correction of Vulpiani KDP/PhiDP retrieval

---

pyart/graph/__init__.py
pyart/graph/_cm_colorblind.py
pyart/graph/cm_colorblind.py
pyart/graph/tests/test_cm_colorblind.py

This PR has the placeholder for the pyart.graph.cm_colorblind class with Cameron Homeyer's colorblind friendly colormap in it.

ADD: Cameron Homeyer's colormap

---

pyart/bridge/wradlib_bridge.py

Fixes the issue #720 brought up by @swnesbitt. Better metadata descriptors for texture of complex phase field.

Comp texture

---

contributors_guide.rst

DOC: Added pyart build in place install for nosetests and added import order list.

---

README.rst
pyart/core/radar.py

Added some badges related to downloads and the Anaconda Cloud. Added mention of the contributor's guide in the contributing section of the README.rst. Updated the documentation in the radar class to address issue #587 mentioned in pull request #555 .

DOC: Changes to documentation in README.rst and radar.py.

---

pyart/io/nexrad_level3.py

"b0b1000000000000000" ->  "0b1000000000000000"

Fix bug in sign calculation

---

pyart/graph/radardisplay.py
pyart/graph/radardisplay_airborne.py
pyart/graph/radarmapdisplay.py
pyart/graph/radarmapdisplay_cartopy.py

The if raster statement checks for 'if not None' False will count as this so set_rasterized will be True.

FIX: Fixes a bug where set_rasterized is always True.

---

pyart/retrieve/gate_id.py

Fix MaskedArray Error in gate_id.py #749

---

pyart/correct/__init__.py
pyart/correct/phase_proc.py
pyart/correct/tests/test_phase_proc.py

Added new methods in phase_proc that will accept a gate filter. I also cleaned
a lot of issues with carry through in the LP sub functions. Will need to
eventually depricate the normal codes and rename

ENH: Gatefiltered LP codes

---

pyart/retrieve/tests/test_vad.py
pyart/retrieve/vad.py
setup.py

Function will crate a VAD profile from a given radar scan. Testing of the code was done by comparing it to known profiles from soundings. The following images are examples of output from the code and overlaying it on top of the sounding data to compare it.

ADD: added a function that will make a VAD profile from a radar scan and a unit test to go along with the function

---

appveyor.yml

Install the packages from the conda-forge channel.

FIX: An attempt to fix basemap pyproj issue.

---

INSTALL.rst

Edited INSTALL.rst: Updated some dependency info and applied rst preformatting syntax for code-like parts to make them look pretty.
Happy Hacktoberfest! ;)

DOC: update dependency info, fix rst preformatting

---

pyart/retrieve/qvp.py

Desired_angle can now be set by the user, if not set by user then a default value is used.

MAINT: changed desired_angle so user can set the radar tilt angle

---

environment.yml
guides/setting_up_an_environment.rst

Basic environment file for pyart and its basic plotting and calculation functions. Instructions on optional dependencies and those requiring path definitions can be found in the guide. The guide goes into detail and anaconda, creating environments from scratch and from an environment.yml and more.

ADD: Adding basic environment file and setting up conda environments rst file.

---

pyart/correct/region_dealias.py

I am fixing an issue where the sounding constraint on the region based dealiasing would crash if there was only one region.

BUG: Region based dealiasing cost function would crash when there was only one region

---

pyart/util/simulated_vel.py

This fixes an error I was getting when using the newest scipy for interpolating the sounding to gates regarding using masked arrays. Now there is a check to see if there are masked arrays before doing the interpolation.

Masked array check in simulated_velocity

---

pyart/graph/radardisplay.py

A fix for issue #819 @scollis @swnesbitt.

FIX: A fix suggested by @scollis for the bug in rhi plotting found by @swnesbitt

---

.travis.yml
continuous_integration/environment-2.7.yml
continuous_integration/environment-3.7.yml
doc/source/conf.py
pyart/core/wind_profile.py
pyart/correct/attenuation.py
pyart/correct/phase_proc.py
pyart/filters/gatefilter.py

Fixed docstrings in few modules that were not being generated with sphinx. Moved doc build to 3.7 since we will be removing support for 2.7 soon.

ENH: Moved doc build to python 3.7 instead of python 2.7. 

---

appveyor.yml
continuous_integration/environment-2.7.yml
continuous_integration/environment-3.5.yml
continuous_integration/environment-3.6.yml
continuous_integration/environment-3.7.yml
pyart/graph/gridmapdisplay.py
pyart/graph/tests/test_gridmapdisplay.py

Changed the GridMapDisplay class to use Xarray and it's plotting functions as well as using Cartopy for getting a basemap  background. Also created unit test for function.

ADD: new GridMapDisplay class that uses Xarray and Cartopy.

---

pyart/core/radar.py
pyart/core/tests/test_radar.py

Mentioned in #808 by @aschueth, function allows the user to specify a sweep and can then obtain the gate latitude, longitude and altitude for that sweep.

ENH: Adding get_gate_lat_lon_alt function.

---

pyart/core/grid.py
pyart/core/tests/test_grid.py
pyart/graph/gridmapdisplay.py

Created a to_xarray function in grid.py. Removed the get_dataset function from gridmapdisplay.py as it did the same thing. Updated unittest for grid.py.
PR is for issue #844

MAINT: Moved get_dataset from gridmapdisplay.py to grid.py and renamed to to_xarray

---

pyart/graph/gridmapdisplay.py
pyart/graph/gridmapdisplay_basemap.py
pyart/graph/radardisplay_airborne.py

Addings the option to define ticks and ticklabels similar to what is
seen in the radarmapdisplay class.

ENH: Adding ticks and ticklabs as parameters.

---

pyart/graph/cm.py
pyart/graph/cm_colorblind.py

Updated the colorblind friendly code to not through the future warnings based on code updates to ACT provided by Ken Kehoe.

FIX: Fixed future warnings for elementwise comparison in colormap code

---

pyart/core/grid.py
pyart/core/tests/test_grid.py
pyart/graph/gridmapdisplay.py
pyart/graph/tests/test_gridmapdisplay.py

Added imshow to plot_grid, need to work on way to get it in plot_longitudinal etc,, but figure pull request now for the fixes. Mask outside wasn't being used in gridmapdisplay ode, so fixed that. to_xarray coords are fixed.

ENH: Added imshow as option for plot_grid and fixed bugs in to_xarray.

---

pyart/core/grid.py

Optional xarray makes it easier to use pyart in space constrained environments

fix(xarray): Gate xarray so its optional

---

pyart/aux_io/odim_h5.py

Fixing issue #895 where the function pyart.aux_io.read_odim_h5 does not close the hdf5 files after reading the file.
I have just added a `with` statement and indented the part of the code below it that is using the hfile descriptor. This should close the opened file properly, even if an error is thrown.

FIX: Closing ODIM h5 files. #895

---

pyart/aux_io/odim_h5.py

FIX: odimh5 range and azimuth sampling

---

pyart/correct/attenuation.py
pyart/correct/phase_proc.py

FIX: Fix to optional doc and warning message for attenuation code.

---

pyart/io/nexrad_level2.py

FIX: Fix for msg29 function extra parameter.

---

examples/plotting/plot_rhi_cfradial.py
examples/plotting/plot_rhi_sigmet.py
examples/plotting/plot_rhi_two_panel.py
pyart/core/tests/test_grid.py
pyart/correct/phase_proc.py
pyart/graph/common.py
pyart/io/cfradial.py
pyart/retrieve/gate_id.py

At the moment isoformat attribute is not found, so setting isoformat using strftime. Also set calendar in fetch sonde time.

FIX: A fix for the update in one of the datetime modules that broke CI

---

setup.py

@scollis , the test will probably fail, but its not related, it due to new cftime release.

MNT: Adding MPL framework classifier, addresses #910.

---

pyart/default_config.py
pyart/io/nexrad_level2.py

I think I got it. The only thing is unit test is based on RDA builds before 19.0, will need to redo the unit tests as it assert values from an older nexrad file from testing directory.

ENH: Updated nexrad for RDA build 19.0.

---

pyart/graph/radardisplay.py
pyart/io/nexradl3_read.py
pyart/io/tests/test_nexrad_level3.py

@dcedgren this should address #922 for nexrad level 3

FIX: This converts the nexrad altitude from feet to meters.

---

pyart/aux_io/odim_h5.py

FIX: Issue #694 when working with ODIM with empty moment.

---

pyart/core/radar.py

"First attempt at a function to compute gate area for a given sweep."

add get_gate_area

---

pyart/io/nexrad_level3.py
pyart/io/nexradl3_read.py

FIX: A fix for the NoneType error with regards to nexrad 3 elevation.

---

pyart/io/_sigmet_noaa_hh.py

Submodule path has changed for np.rec.frombuffer, causing import issues. Changing to proper path.

FIX: Fix addressed for #962 by mwilson14.

---

pyart/default_config.py

This is to maintain cfradial ARM standards.

MNT: Update to default config to fix units, and add field info for attenuation fields.

---

pyart/aux_io/gamic_hdf5.py
pyart/aux_io/gamicfile.py

Have a check for earleir versions of h5py in the meantime but changes
should work for newer and earlier versions

FIX: Fix for h5py > 3.0 decoding of str.

---

pyart/aux_io/sinarame_h5.py

Fixes the removal of cftime utime legacy code, reproduces similar cftime use in other modules. Fixes #993

FIX: Fix for cftime 1.5 release.

---

README.rst

Update of the button and test of CI for travis.

DOC: Update of travis link.

---

pyart/retrieve/__init__.py
pyart/retrieve/tests/test_vad.py
pyart/retrieve/vad.py

Added browning vad code as a addition to vad suite as well as a temp replacement for the vad code that is having incorrect results as I continue working on a solution.

ENH: Adding browning vad code as a replacement.

---

pyart/graph/radardisplay.py

Code fails with one sweep with new matplotlib checks due to mismatch, temp fix for mistmatch until I found a better check for such cases.

FIX: Fix for azimuth_rhi_plot.

---

pyart/aux_io/radx_grid.py

Changes allow for a better coverage of files.

MNT: RadxGrid Fix for working with different files.

---

pyart/graph/radarmapdisplay.py
pyart/graph/tests/test_radarmapdisplay.py
pyart/io/mdv_common.py
pyart/io/output_to_geotiff.py
pyart/io/tests/test_uf_write.py
pyart/io/uf_write.py
pyart/map/grid_mapper.py

Multiple fixes for warnings appearing in CI. Also using this as a tests to see if test files are working correctly.

DEP: Multiple fixes for deprecation warnings.

---

doc/source/conf.py

Similar to the ACT repo, add analytics to the PyART Docs

Add Google Analytics

---

examples/plotting/plot_three_panel_gridmapdisplay.py

Update issue with subplots in GridMapDisplay

---

pyart/default_config.py
pyart/filters/tests/test_gatefilter.py

Will be adding two more tests functions to this PR soon.

TST: Adding more tests to gatefilter.

---

doc/source/conf.py

This adds a sidebar that makes blog posts searchable, including an interactive word cloud.

Add blog sidebar

---

doc/source/conf.py

Currently, the analytics are not uploading properly - this tag fixes that

Fix bug in analytics ID

---

examples/mapping/compare_two_radars_gatemapper.py

This adds an example for the recently added GateMapper functionality

Add an example for Gatemapper

---

doc/source/changelog.md
doc/source/conf.py
doc/source/index.rst

This adds a changelog to the docs

Add changelog section

---

doc/source/blog_posts/2022/plot-nexrad-level3.ipynb
doc/source/conf.py

There was a typo in the first line of the post - this fixes that and adds back in the postcard view for each post.

Fix typo and back in postcard

---

codecov.yml
pyart/retrieve/tests/test_echo_class.py

Add more tests for the retrieval module

Add more tests for test_echo_class

---

pyart/default_config.py
pyart/io/nexrad_level3.py

Fixes the incorrect units and incorrect dealing of 16 bit integers from the NEXRAD Level 3 DPR data
Closes #1114

FIX: Fix IO for NEXRAD Level 3 instantaneous precipitation rate (DPR)

---

.github/workflows/pypi-release.yml

We need an extra package to actually run the build here

FIX: Add build package to pypi release

---

.github/workflows/pypi-release.yml

After testing over in a [test-actions](https://github.com/mgrover1/test-actions/blob/master/.github/workflows/test_flow.yml) repo, this should work!

FIX: fix the pypi build

---

doc/source/blog_posts/2022/first_pullrequest.ipynb

Quick change of a few Jupyter-Notebook cell types that I did not catch during the first PR request. Changing code snippets from markdown cells to code cells to be consistent across the entire blog post.

DOC: Quick change of a few Jupyter-Notebook cell types 

---

pyart/graph/tests/test_gridmapdisplay.py

Running into errors with Xarray being a dependency.

MNT: Changing dependency check to Cartopy.

---

pyart/util/simulated_vel.py
pyart/util/tests/test_simulated_vel.py

When using sonde profiles, when it resets the variable with the same name, get issues due to the shape mismatch. Creating an array with same shape as the no_nan array.

FIX: Fixes an issue with mismatch arrays.

---

doc/source/changelog.md

We are currently missing the changelog for the latest release- this adds it in.

ADD: Update Changelog for v1.12.2

---

continuous_integration/environment-ci.yml
requirements.txt

Pin version of xarray

---

pyart/util/xsect.py

This fixes an issue in visualizing RHI scans generated from PPI scans.

FIX: Fix sorting issue with elevations and azimuths

---

examples/plotting/plot_nexrad_multiple_moments.py

Plot colormap is barely visible, updating vmin and vmax.

MNT: Update vmin vmax to make velocity plot more visible.

---

pyart/util/columnsect.py

For each radar column, calculated the sequential time (time since the start of the radar volume + time within the center of the ray of the associated gate) for each height gate above the given location. 
Added this sequential time as a new coordinate within the Xarray Dataset output. 
Added pandas import for handing time deltas for calculating time.

ENH: Addition of Time as a Coordinate within extracted column output

---

pyart/__init__.py

FIX: Fix incorrect version showing up in docs (API)

---

pyart/graph/common.py
pyart/graph/radardisplay.py

After gathering feedback from @srbrodzik, this seems like a better approach to dealing with RHI scans that are close to 270 degrees.

FIX: Add revised fix for RHI near 270

---

continuous_integration/environment-ci.yml
doc/environment.yml
requirements.txt

Fix the issue with new numpy version and cftime

FIX: Update requirements with cftime + numpy

---

doc/source/userguide/index.rst

Add a reference to cookbooks in the user guide section

ADD: Add cookbook section in user guide

---

README.rst

Add pyrad to the list of related projects.
@jfigui does this look correct?

Add pyrad to the readme

---

doc/source/changelog.md

Update the changelog from the previous versions of Py-ART

ADD: Add changelog from previous releases

---

examples/plotting/plot_choose_a_colormap.py

Add a new colormap example to our docs
Closes #1282

DOC: Add a new colormap example

---

examples/plotting/plot_choose_a_colormap.py

There is a list I forgot to remove from the example - this takes care of that.

FIX: Remove old list of colormaps

---

doc/source/userguide/index.rst

Update the new link to the radar cookbook

FIX: Update link to cookbooks

---

tests/map/test_gates_to_grid.py
tests/map/test_grid_mapper.py

Assign boolean to list, not boolean

---

pyart/config.py

Closes #1368 
After some digging, this solves the issue.

MNT: Move to exec_module instead of load_module

---

pyart/__init__.py

Change how we automatically deal with warnings
Closes #1371

Remove deprecation line in init file

---

.github/workflows/ci.yml
.pre-commit-config.yaml
continuous_integration/environment-ci.yml
pyart/__init__.py
pyart/default_config.py
pyart/io/cfradial.py
pyart/retrieve/gate_id.py
pyproject.toml
scripts/check_cfradial
setup.cfg

Use ruff for linting
Closes #1387

ENH: Add ruff python linting

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Add issue, PR templates
Also add codeowners file which will assign reviewers to PRs

ADD: Add codeowners, issue, and pr template

---

pyart/retrieve/vad.py

Removing VAD warning after comparison, VAD issue will be moved to discussion.

MNT: Remove VAD warning.

---

.github/workflows/wheels.yml
INSTALL.rst
README.rst

CI: Remove python 3.8 and update documentation to reflect releases and CI testing.

---

pyart/io/cfradial.py

ADD: Add cfradial 1.4 version to io

---

continuous_integration/environment-ci.yml
doc/environment.yml
pyart/__init__.py
pyart/io/cfradial.py
pyart/xradar/__init__.py
pyart/xradar/accessor.py
requirements.txt
tests/xradar/test_accessor.py

Add the first part of the Py-ART - Xradar integration, using some of the more common functions of the radar object

Add xradar accessor class

---

requirements.txt

ADD: Add open radar data as a dependency

---

environment.yml
requirements.txt

Add xradar as a dependency

---

pyart/map/gates_to_grid.py

fix: memory leak in grid mappers

---

pyart/io/nexrad_common.py
tests/io/test_nexrad_archive_msg1.py

Ensure units are in feet for nexrad references

---

pyart/retrieve/vad.py

Fix masking issue in VAD michelson

---

examples/xradar/plot_grid_xradar.py

Add an example showcasing using xradar and Py-ART's gridding algorithms

DOC: Add xradar gridding example

---

examples/xradar/plot_dealias_xradar.py

Add an example dealiasing velocity data with xradar + Py-ART

DOC: Add dealias example with xradar

---

.github/dependabot.yml

Adds dependabot to update new versions of github actions workflows

ADD: Add dependabot to track new github actions

---

pyart/correct/attenuation.py
pyart/correct/region_dealias.py

Fix warning messages for future deprecations of scipy/numpy features

FIX: Fix warning errors for scipy and numpy

---

pyart/aux_io/sinarame_h5.py

Note: I'm not sure if this is the most efficient or best way for this, so can see what others have to add.

ENH: Add instrument parameter check for sinarame.

---

pyart/xradar/accessor.py
tests/xradar/test_accessor.py

Add `get_azimuth` method to xradar bridge

FIX: Add get_azimuth xradar

---

pyart/io/sigmet.py
tests/io/test_sigmet.py

Add a calculated frequency field from the wavelength in sigmet

ADD: Add frequency in sigmet/iris IO

---

pyproject.toml
setup.py

Add updated numpy cython flags, ensure newer versions of cython are used.

ADD: Add updated cython and flags for numpy

---

pyart/graph/radardisplay.py
pyart/io/_sigmetfile.pyx
pyart/io/cfradial.py
pyart/io/chl.py
pyart/io/grid_io.py
pyart/io/nexrad_level3.py
pyart/io/output_to_geotiff.py
pyart/util/columnsect.py
pyart/xradar/accessor.py
tests/graph/test_radarmapdisplay.py

Fixes for the code where we were getting multiple warnings. This includes the new datetime syntax, xarray dims to sizes, stamen depreciation and more.

FIX: Update for multiple warnings.

---

pyart/map/grid_mapper.py
tests/map/test_grid_mapper.py

Fix an existing issues for dimensionality with grids

FIX: Fix dimensions for grid origin

---

pyart/correct/attenuation.py

Doc change was suggested in #931

DOC: Update the attenuation docs to reflect where the formula comes from.

---

.github/workflows/wheels.yml

CI: Update wheels to use macos14.

---

.github/workflows/wheels.yml

Ensure apple builds are not duplicated + overwriting each other

FIX: Ensure apple builds on its own systems

---

pyart/config.py

Fix the config module to use the latest API changes for matplotlib

FIX: Add fix for matplotlib updated version

---

examples/correct/plot_cloud_mask.py

Fixes the incorrect field being plotted in the cloud mask example

FIX: Incorrect field plotted in cloud mask example

---

.github/workflows/ci.yml
continuous_integration/environment-ci.yml

Add a few lines of extra configuration to resolve issues related to CI runs

ADD: Add a few lines to ci workflow to resolve issues

---

continuous_integration/environment-ci.yml
doc/environment.yml

Add dask to the documentation environment

ADD: Add dask to docs environment

---

doc/source/conf.py

Fix the gallery build by removing nbsphinx

FIX: Fix the gallery build issue with new sphinx

---

doc/environment.yml
pyart/io/_sigmetfile.pyx

See discussion here:
https://github.com/ARM-DOE/pyart/discussions/1706

FIX: Update sigmet reader to handle 1byte kdp, that needs to be divided by wavelength.

---

pyart/correct/dealias.py
setup.py

Remove FourDD dealiasing in Py-ART 2.0 branch

DEL: Remove the fourdd functionality in pyart-2-0

---

pyart/io/_sigmetfile.pyx

Can reopen discussion if need be.

FIX: Fix for wavelength not being converted 1/100

---

pyart/xradar/accessor.py
tests/xradar/test_accessor.py

Add missing add_field_like method to xradar accessor

ADD: Add add_field_like method to xradar

---

pyart/testing/example_data.py

Add header logic to access data from ADC

FIX: Add header logic to download to resolve ADC data access issue

---

examples/plotting/plot_max_cappi.py

Fixes linting failure in CI post PR merge

STY: PEP8 fixes post PR merge

---

CONTRIBUTING.rst
README.rst

DOC: Updating contributor's guide of open-radar-data example file usage.

---

pyart/map/grid_mapper.py

FIX: Update grid_rhi to use abs and both x and y

---

doc/environment.yml
examples/io/plot_nexrad_data_google_cloud.py

DOC: Adding new example on working with google cloud nexrad.

---

CONTRIBUTING.rst

- [ X] Documentation reflects changes

DOC: fix broken numpy link on contributor's guide

---

INSTALL.rst
README.rst
doc/source/index.rst

DOC: Update dependency list.

---

pyart/retrieve/qvp.py

Removed some errant print lines in the QVP code. Discovered by @ScottGiangrande

FIX: Fixed prints in QVP. These are no longer needed for debugging Closing #1758

---

pyart/aux_io/odim_h5.py

MNT: Update to check for metadata in ODIM reader

---

examples/io/plot_nexrad_data_google_cloud.py

DOC: Update example text.

---

examples/correct/plot_dealias_rhi.py

Add an example for dealiasing RHI data with the region-based algorithm

DOC: Add example for dealiasing rhi data

---

INSTALL.rst

Add pixi as recommended installation method

DOC: Add pixi suggestion to docs

---

doc/source/conf.py
doc/source/userguide/index.rst
doc/source/userguide/overview.rst

DOC: Add new why py-art guide
